### ISSUE TITLE
Build fails after upgrade to 3.2 on Read Secrets

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL-Go#665] opened 2023-08-17 08:58 UTC
On the CI/CD build after updating to al-go 3.2 the build fails on the Read Secrets step. Other repos are successful.
A quick work-around would be appreciated 🙂

I'm including the Read Settings as I think the issue is having multiple entries in _appDependencyProbingPaths_ 
Let me know if you want access to the repo.

### Read settings

```
Run microsoft/AL-Go-Actions/ReadSettings@v3.2
  with:
    shell: powershell
    parentTelemetryScopeJson: 7b22506[1](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:3:1)7[2](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:3:2)616d657465727[3](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:3:3)223a7b7d2c22[4](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:3:4)[5](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:3:5)[6](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:3:6)d69[7](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:3:7)4746564223a66616c73652c22436f7272656c6174696f6e4964223a22373[8](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:3:8)3534363162302d65353[9](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:3:9)332d346438352d396135392d303930313235343364663137222c22506172656e744964223a22222c22416c6c506172616d6574657273223a7b7d2c22546f704964223a2237383534363162302d653539332d346438352d396135392d303930313235343364663137222c224e616d65223a22414c2d476f20776f726b666c6f772072616e3a2043494344222c22537461727454696d65223a225c2f446174652831363932323630373639333433295c2f222c2250726f70657274696573223a7b226576656e744964223a22444f30303931222c226263436f6e7461696e657248656c70657256657273696f6e223a22352e302e35222c22697341646d696e6973747261746f72223a2254727565222c22737461636b5472616365223a225b5c6e2020496e697454656c656d6574727953636f70652061742054656c656d6574727948656c7065722e7073313a206c696e65203231345c6e202043726561746553636f70652061742054656c656d6574727948656c7065722e70736d313a206c696e652037355c6e2020576f726b666c6f77496e697469616c697a652e70733120617420576f726b666c6f77496e697469616c697a652e7073313a206c696e652033345c6e202063343534353735612d383334332d343430662d613635312d6264623330336364303233622e7073312061742063343534353735612d383334332d343430662d613635312d6264623330336364303233622e7073313a206c696e6520345c6e20205c7530303363536372697074426c6f636b5c7530303365206174205c75303033634e6f2066696c655c75303033655c6e5d222c22414c476f56657273696f6e223a2276332e32222c2274797065223a22417070536f7572636520417070222c2274656d706c61746555726c223a2268747470733a2f2f6769746875622e636f6d2f6d6963726f736f66742f414c2d476f2d417070536f75726365406d61696e222c227265706f7369746f7279223a227072796d65476c6f62616c2f7072796d654d617474657273222c2272756e417474656d7074223a2231222c2272756e4e756d626572223a22313135222c2272756e4964223a2235383838353438353132227d2c224576656e744964223a22444f30303931227d
    project: .
    get: useCompilerFolder,keyVaultCodesignCertificateName,doNotSignApps,artifact
    actor: AskeHolst
    token: ***
    includeProduction: N
    release: N
Run $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
  $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
  try {
    C:\2\_work\_actions\microsoft\AL-Go-Actions\v3.2\ReadSettings/ReadSettings.ps1 -actor $ENV:_actor -token $ENV:_token -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson -project $ENV:_project -getenvironments $ENV:_getenvironments -includeProduction ($ENV:_includeProduction -eq 'Y') -release ($ENV:_release -eq 'Y') -get $ENV:_get
  }
  catch {
    Write-Host "::ERROR::Unexpected error when running action. Error Message: $($_.Exception.Message.Replace("`r",'').Replace("`n",' ')), StackTrace: $($_.ScriptStackTrace.Replace("`r",'').Replace("`n",' <- '))";
    exit 1
  }
  shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"
  env:
    _actor: AskeHolst
    _token: ***
    _parentTelemetryScopeJson: 7b22506172616d6574657273223a7b7d2c22456d6974746564223a66616c73652c22436f7272656c6174696f6e4964223a2237383534363162302d653539332d346438352d396135392d303930313235343364663137222c22506172656e744964223a22222c22416c6c506172616d6574657273223a7b7d2c22546f704964223a2237383534363162302d653539332d346438352d396135392d303930313235343364663137222c224e616d65223a22414c2d476f20776f726b666c6f772072616e3a2043494344222c22537461727454696d65223a225c2f446174652831363932323630373639333433295c2f222c2250726f70657274696573223a7b226576656e744964223a22444f30303931222c226263436f6e7461696e657248656c70657256657273696f6e223a22352e302e35222c22697341646d696e6973747261746f72223a2254727565222c22737461636b5472616365223a225b5c6e2020496e697454656c656d6574727953636f70652061742054656c656d6574727948656c7065722e7073313a206c696e65203231345c6e202043726561746553636f70652061742054656c656d6574727948656c7065722e70736d313a206c696e652037355c6e2020576f726b666c6f77496e697469616c697a652e70733120617420576f726b666c6f77496e697469616c697a652e7073313a206c696e652033345c6e202063343534353735612d383334332d343430662d613635312d6264623330336364303233622e7073312061742063343534353735612d383334332d343430662d613635312d6264623330336364303233622e7073313a206c696e6520345c6e20205c7530303363536372697074426c6f636b5c7530303365206174205c75303033634e6f2066696c655c75303033655c6e5d222c22414c476f56657273696f6e223a2276332e32222c2274797065223a22417070536f7572636520417070222c2274656d706c61746555726c223a2268747470733a2f2f6769746875622e636f6d2f6d6963726f736f66742f414c2d476f2d417070536f75726365406d61696e222c227265706f7369746f7279223a227072796d65476c6f62616c2f7072796d654d617474657273222c2272756e417474656d7074223a2231222c2272756e4e756d626572223a22313135222c2272756e4964223a2235383838353438353132227d2c224576656e744964223a22444f30303931227d
    _project: .
    _getenvironments: 
    _includeProduction: N
    _release: N
    _get: useCompilerFolder,keyVaultCodesignCertificateName,doNotSignApps,artifact
Downloading BcContainerHelper latest version from CDN
BcContainerHelper version 5.0.5
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Applying settings from C:\2\_work\prymeMatters\prymeMatters\.github\AL-Go-Settings.json
Applying settings from C:\2\_work\prymeMatters\prymeMatters\.AL-Go\settings.json
SETTINGS:
{
    "keyVaultCertificateUrlSecretName":  "",
    "microsoftTelemetryConnectionString":  "[REDACTED]",
    "type":  "AppSource App",
    "sendExtendedTelemetryToMicrosoft":  false,
    "appBuild":  115,
    "installTestApps":  [

                        ],
    "versioningStrategy":  0,
    "installApps":  [
                        "[REDACTED]"
                    ],
    "installTestLibraries":  false,
    "runNumberOffset":  0,
    "codeSignCertificatePasswordSecretName":  "codeSignCertificatePassword",
    "country":  "gb",
    "partnerTelemetryConnectionString":  "",
    "insiderSasTokenSecretName":  "insiderSasToken",
    "doNotRunTests":  false,
    "runs-on":  "windows-latest",
    "configPackages":  [

                       ],
    "generateDependencyArtifact":  false,
    "templateUrl":  "https://github.com/microsoft/AL-Go-AppSource@main",
    "keyVaultCertificatePasswordSecretName":  "",
    "rulesetFile":  "",
    "licenseFileUrlSecretName":  "licenseFileUrl",
    "memoryLimit":  "",
    "keyVaultClientIdSecretName":  "",
    "testFolders":  [

                    ],
    "githubRunner":  "windows-latest",
    "doNotBuildTests":  false,
    "environments":  [

                     ],
    "companyName":  "",
    "assignPremiumPlan":  false,
    "artifact":  "",
    "ghTokenWorkflowSecretName":  "ghTokenWorkflow",
    "enableTaskScheduler":  false,
    "enableCodeCop":  true,
    "repoVersion":  "4.1",
    "doNotPublishApps":  false,
    "doNotSignApps":  false,
    "unusedALGoSystemFiles":  [

                              ],
    "githubRunnerShell":  "powershell",
    "cacheKeepDays":  3,
    "bcptTestFolders":  [

                        ],
    "updateDependencies":  false,
    "cacheImageName":  "my",
    "treatTestFailuresAsWarnings":  false,
    "AppSourceProductId":  "[REDACTED]",
    "additionalCountries":  [

                            ],
    "enableUICop":  true,
    "customCodeCops":  [

                       ],
    "appDependencies":  [

                        ],
    "doNotRunBcptTests":  false,
    "appDependencyProbingPaths":  [
                                      {
                                          "authTokenSecret":  "GHTOKENWORKFLOW",
                                          "projects":  "*",
                                          "release_status":  "release",
                                          "repo":  "https://github.com/prymeGlobal/prymeSystem",
                                          "version":  "latest"
                                      },
                                      {
                                          "authTokenSecret":  "GHTOKENWORKFLOW",
                                          "projects":  "*",
                                          "release_status":  "latestBuild",
                                          "repo":  "https://github.com/prymeGlobal/prymeTime"
                                      }
                                  ],
    "useCompilerFolder":  false,
    "installTestFramework":  false,
    "keyVaultCodesignCertificateName":  "",
    "keyVaultName":  "",
    "installOnlyReferencedApps":  true,
    "obsoleteTagMinAllowedMajorMinor":  "",
    "applicationDependency":  "[18](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:3:19).0.0.0",
    "applicationInsightsConnectionStringSecretName":  "applicationInsightsConnectionString",
    "shell":  "powershell",
    "failOn":  "error",
    "projects":  [

                 ],
    "testDependencies":  [

                         ],
    "appRevision":  0,
    "codeSignCertificateUrlSecretName":  "codeSignCertificateUrl",
    "vsixFile":  "",
    "useProjectDependencies":  false,
    "appSourceCopMandatoryAffixes":  [
                                         "LPPEU"
                                     ],
    "buildModes":  [

                   ],
    "templateBranch":  "",
    "installPerformanceToolkit":  false,
    "PullRequestTrigger":  "pull_request_target",
    "appFolders":  [

                   ],
    "repoName":  "prymeMatters",
    "alwaysBuildAllProjects":  false,
    "skipUpgrade":  false,
    "currentSchedule":  "0 2 * * THU",
    "installTestRunner":  false,
    "adminCenterApiCredentialsSecretName":  "adminCenterApiCredentials"
}
GitHubRunnerJson="windows-latest"
GitHubRunnerShell=powershell
Removing BcContainerHelper
```

### Read secrets
```
Run microsoft/AL-Go-Actions/ReadSecrets@v3.[2](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:4:2)
  with:
    shell: powershell
    parentTelemetryScopeJson: 7b22506172616d657465727[3](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:4:3)223a7b7d2c22[4](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:4:4)[5](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:4:5)[6](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:4:6)d69[7](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:4:7)4746564223a66616c73652c22436f7272656c6174696f6e4964223a22373[8](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:4:8)3534363162302d65353[9](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:4:9)332d346438352d396135392d303930313235343364663137222c22506172656e744964223a22222c22416c6c506172616d6574657273223a7b7d2c22546f704964223a2237383534363162302d653539332d346438352d396135392d303930313235343364663137222c224e616d65223a22414c2d476f20776f726b666c6f772072616e3a2043494344222c22537461727454696d65223a225c2f446174652831363932323630373639333433295c2f222c2250726f70657274696573223a7b226576656e744964223a22444f30303931222c226263436f6e7461696e657248656c70657256657273696f6e223a22352e302e35222c22697341646d696e6973747261746f72223a2254727565222c22737461636b5472616365223a225b5c6e2020496e697454656c656d6574727953636f70652061742054656c656d6574727948656c7065722e7073313a206c696e65203231345c6e202043726561746553636f70652061742054656c656d6574727948656c7065722e70736d313a206c696e652037355c6e2020576f726b666c6f77496e697469616c697a652e70733120617420576f726b666c6f77496e697469616c697a652e7073313a206c696e652033345c6e202063343534353735612d383334332d343430662d613635312d6264623330336364303233622e7073312061742063343534353735612d383334332d343430662d613635312d6264623330336364303233622e7073313a206c696e6520345c6e20205c7530303363536372697074426c6f636b5c7530303365206174205c75303033634e6f2066696c655c75303033655c6e5d222c22414c476f56657273696f6e223a2276332e32222c2274797065223a22417070536f7572636520417070222c2274656d706c61746555726c223a2268747470733a2f2f6769746875622e636f6d2f6d6963726f736f66742f414c2d476f2d417070536f75726365406d61696e222c227265706f7369746f7279223a227072796d65476c6f62616c2f7072796d654d617474657273222c2272756e417474656d7074223a2231222c2272756e4e756d626572223a22313135222c2272756e4964223a2235383838353438353132227d2c224576656e744964223a22444f30303931227d
    gitHubSecrets: {
    "STORAGECONTEXT": "***",
    "AZURE_STORAGE_CONNECTION_STRING": "***",
    "NEXT_NEXT_RELEASE_AUTHCONTEXT": "***",
    "AZURE_CREDENTIALS": "***",
    "github_token": "***",
    "AZURE_RESOURCE_GROUP": "***"
  }
    getSecrets: licenseFileUrl,insiderSasToken,codeSignCertificateUrl,codeSignCertificatePassword,keyVaultCertificateUrl,keyVaultCertificatePassword,keyVaultClientId,gitHubPackagesContext,applicationInsightsConnectionString,appDependencyProbingPathsSecrets
  env:
    artifact: 
    keyVaultCodesignCertificateName: 
    doNotSignApps: False
    useCompilerFolder: False
    Settings: {"keyVaultCertificateUrlSecretName":"","microsoftTelemetryConnectionString":"InstrumentationKey=84bd9223-67d4-4378-8590-9e4a46023be2;IngestionEndpoint=https://westeurope-1.in.applicationinsights.azure.com/","type":"AppSource App","sendExtendedTelemetryToMicrosoft":false,"appBuild":115,"installTestApps":[],"versioningStrategy":0,"installApps":["https://prymeartifacts.file.core.windows.net/external/PGS-latest.zip?sv=2021-08-06\u0026st=2022-11-03T[10](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:4:10)%3A19%3A32Z\u0026se=2023-[11](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:4:11)-04T10%3A19%3A00Z\u0026sr=f\u0026sp=r\u0026sig=r9K8IHAFkmNUfvQ%2BKjjeO0QqvDPKQtxeqpL%2FhMVAh0c%3D"],"installTestLibraries":false,"runNumberOffset":0,"codeSignCertificatePasswordSecretName":"codeSignCertificatePassword","country":"gb","partnerTelemetryConnectionString":"","insiderSasTokenSecretName":"insiderSasToken","doNotRunTests":false,"runs-on":"windows-latest","configPackages":[],"generateDependencyArtifact":false,"templateUrl":"https://github.com/microsoft/AL-Go-AppSource@main","keyVaultCertificatePasswordSecretName":"","rulesetFile":"","licenseFileUrlSecretName":"licenseFileUrl","memoryLimit":"","keyVaultClientIdSecretName":"","testFolders":[],"githubRunner":"windows-latest","doNotBuildTests":false,"environments":[],"companyName":"","assignPremiumPlan":false,"artifact":"","ghTokenWorkflowSecretName":"ghTokenWorkflow","enableTaskScheduler":false,"enableCodeCop":true,"repoVersion":"4.1","doNotPublishApps":false,"doNotSignApps":false,"unusedALGoSystemFiles":[],"githubRunnerShell":"powershell","cacheKeepDays":3,"bcptTestFolders":[],"updateDependencies":false,"cacheImageName":"my","treatTestFailuresAsWarnings":false,"AppSourceProductId":"5db87f88-943c-43b3-a743-9b69bab98aa5","additionalCountries":[],"enableUICop":true,"customCodeCops":[],"appDependencies":[],"doNotRunBcptTests":false,"appDependencyProbingPaths":[{"authTokenSecret":"GHTOKENWORKFLOW","projects":"*","release_status":"release","repo":"https://github.com/prymeGlobal/prymeSystem","version":"latest"},{"authTokenSecret":"GHTOKENWORKFLOW","projects":"*","release_status":"latestBuild","repo":"https://github.com/prymeGlobal/prymeTime"}],"useCompilerFolder":false,"installTestFramework":false,"keyVaultCodesignCertificateName":"","keyVaultName":"","installOnlyReferencedApps":true,"obsoleteTagMinAllowedMajorMinor":"","applicationDependency":"[18](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:4:18).0.0.0","applicationInsightsConnectionStringSecretName":"applicationInsightsConnectionString","shell":"powershell","failOn":"error","projects":[],"testDependencies":[],"appRevision":0,"codeSignCertificateUrlSecretName":"codeSignCertificateUrl","vsixFile":"","useProjectDependencies":false,"appSourceCopMandatoryAffixes":["LPPEU"],"buildModes":[],"templateBranch":"","installPerformanceToolkit":false,"PullRequestTrigger":"pull_request_target","appFolders":[],"repoName":"prymeMatters","alwaysBuildAllProjects":false,"skipUpgrade":false,"currentSchedule":"0 2 * * THU","installTestRunner":false,"adminCenterApiCredentialsSecretName":"adminCenterApiCredentials"}
Run $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
Downloading BcContainerHelper latest version from CDN
BcContainerHelper version 5.0.5
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Masking value for clientSecret
Trying to get the secret(licenseFileUrl) from the github environment.
Trying to get the secret(licenseFileUrl) from Key Vault (pryme-cicd).
Az.KeyVault Module is available in version 4.9.1
Using Az.KeyVault version 4.9.1
Masking value for clientSecret
Successfully connected to Azure Key Vault.
Masking value for licenseFileUrl
Secret(licenseFileUrl) was retrieved from the Key Vault.
licenseFileUrl successfully read from secret licenseFileUrl
Trying to get the secret(insiderSasToken) from the github environment.
Trying to get the secret(insiderSasToken) from Key Vault (pryme-cicd).
Masking value for insiderSasToken
Secret(insiderSasToken) was retrieved from the Key Vault.
insiderSasToken successfully read from secret insiderSasToken
Trying to get the secret(codeSignCertificateUrl) from the github environment.
Trying to get the secret(codeSignCertificateUrl) from Key Vault (pryme-cicd).
Masking value for codeSignCertificateUrl
Secret(codeSignCertificateUrl) was retrieved from the Key Vault.
codeSignCertificateUrl successfully read from secret codeSignCertificateUrl
Trying to get the secret(codeSignCertificatePassword) from the github environment.
Trying to get the secret(codeSignCertificatePassword) from Key Vault (pryme-cicd).
Masking value for codeSignCertificatePassword
Secret(codeSignCertificatePassword) was retrieved from the Key Vault.
codeSignCertificatePassword successfully read from secret codeSignCertificatePassword
Trying to get the secret(gitHubPackagesContext) from the github environment.
Trying to get the secret(gitHubPackagesContext) from Key Vault (pryme-cicd).
Could not find secret gitHubPackagesContext in Github secrets or Azure Key Vault.
Trying to get the secret(applicationInsightsConnectionString) from the github environment.
Trying to get the secret(applicationInsightsConnectionString) from Key Vault (pryme-cicd).
Could not find secret applicationInsightsConnectionString in Github secrets or Azure Key Vault.
Trying to get the secret(GHTOKENWORKFLOW) from the github environment.
Trying to get the secret(GHTOKENWORKFLOW) from Key Vault (pryme-cicd).
Masking value for GHTOKENWORKFLOW
Secret(GHTOKENWORKFLOW) was retrieved from the Key Vault.
GHTOKENWORKFLOW successfully read from secret GHTOKENWORKFLOW
Trying to get the secret(GHTOKENWORKFLOW) from the github environment.
Trying to get the secret(GHTOKENWORKFLOW) from Key Vault (pryme-cicd).
Masking value for GHTOKENWORKFLOW
Secret(GHTOKENWORKFLOW) was retrieved from the Key Vault.
AL-Go action ran: ReadSecrets Telemetry Correlation Id: 7b8d7a1b-7ff7-4b36-87b3-65cf0ccf118f
Removing BcContainerHelper
Error: Unexpected error when running action. Error Message: Item has already been added. Key in dictionary: 'GHTOKENWORKFLOW'  Key being added: 'GHTOKENWORKFLOW', StackTrace: at <ScriptBlock>, C:\2\_work\_actions\microsoft\AL-Go-Actions\v3.2\ReadSecrets\ReadSecrets.ps1: line 101 <- at <ScriptBlock>, C:\2\_work\_actions\microsoft\AL-Go-Actions\v3.2\ReadSecrets\ReadSecrets.ps1: line 72 <- at <ScriptBlock>, C:\2\_work\_temp\[52](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:4:54)6eed[80](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:4:82)-d[83](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:4:85)6-40[86](https://github.com/prymeGlobal/prymeMatters/actions/runs/5888548512/job/15970007843#step:4:88)-803a-1c6fc34ed7c4.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1
Error: Process completed with exit code 1.
```

**Comment by freddydk** [comment] 2023-08-17 09:37
No, that is not the issue.
The issue is that you have two appDependencyProbingPaths, which uses the same authToken.
You probably cannot fix this yourself - this needs a hotfix.

![image](https://github.com/microsoft/AL-Go/assets/10775043/b9adb09e-0a53-4702-80fb-bc6ce02309cd)

**Comment by freddydk** [comment] 2023-08-17 10:12
The workflow should work again when the above hotfix has been reviewed and merged.

**Comment by freddydk** [comment] 2023-08-17 10:13
Which should be done now, please re-run to verify.
Thanks

**Comment by AskeHolst** [comment] 2023-08-17 10:23
Thank you, it works perfectly now.

**Closed** 2023-08-17 11:09 UTC
Labels: bug
