### ISSUE TITLE
Deployment to QA environment fails

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#644] opened 2023-08-03 08:29 UTC
Hey @freddydk , 

I do have a strange issue again with deployment again

It gives me an error 

```
Exception calling "GetResult" with "0" argument(s): "An error occurred while sending the request."
An error occurred while sending the request.
The underlying connection was closed: An unexpected error occurred on a receive.
```

![image](https://github.com/microsoft/AL-Go/assets/16342128/73154950-685e-4e43-b143-8808602fd3a7)
 
But it actually succeeds to publish/install extension.
![image](https://github.com/microsoft/AL-Go/assets/16342128/ea34c509-4580-4b33-916e-c9bfb1bb9a45)

Have you seen this behavior before?

Best Regards, 
Gintautas

**Comment by gntpet** [comment] 2023-08-03 17:46
I think i managed to narrow the problem with similiar script you use for deployment:

```
$bcAuthContext = New-BcAuthContext -includeDeviceLogin 
$envName = 'SRSQA'
$apps = @((Get-ChildItem -Path C:\Users\G.Petkevicius2\Downloads\SRS.core-main-Apps-1.0.540.0) | ForEach-Object { $_.FullName })
Publish-PerTenantExtensionApps -bcAuthContext $bcAuthContext -environment $envName -appFiles $apps
```

if i run it for the first time in my powershell session, it works correctly and publishes extensions (or crashes with proper messages, like breaking changes & etc).

when i run it for the second time with the same session, then it uses refresh token & crashes with Unauthorized error

![image](https://github.com/microsoft/AL-Go/assets/16342128/3b90eb8e-6477-44ae-b8c3-a3c6cb08af9c)

in the deployment pipeline I see it is also using refresh token. Did something change in this area recently?

**Comment by freddydk** [comment] 2023-08-03 20:01
I will investigate this tomorrow.

**Comment by gntpet** [comment] 2023-08-04 06:48
Thanks, 

I have few more updates. I tried to switch to another user, thinking that perhaps my users is wrong.  This leads to the different error & no extension getting published at all:

```
Status Code InternalServerError : Internal Server Error
Object reference not set to an instance of an object.
```

![image](https://github.com/microsoft/AL-Go/assets/16342128/a6c064d1-6f9b-401a-887b-ed12a127e909)

I tried to do the same from powershell, and this time using **Publish-BcContainerApp** like you do in deploy.ps1

```
$bcAuthContext = New-BcAuthContext -includeDeviceLogin 
$envName = 'SRSQA'
$apps = @((Get-ChildItem -Path C:\Users\G.Petkevicius2\Downloads\SRS.core-main-Apps-1.0.542.0) | ForEach-Object { $_.FullName })

Publish-BcContainerApp -bcAuthContext $bcAuthContext -environment $envName -appFile $apps -useDevEndpoint -checkAlreadyInstalled
```

I receive the same error
![image](https://github.com/microsoft/AL-Go/assets/16342128/42a6ff1a-16fb-4257-ba09-b23f2cabce3d)

which breaks here
![image](https://github.com/microsoft/AL-Go/assets/16342128/7730a0e8-5de5-4a98-b70d-97e0c22aa621)

hope this helps in your research

**Comment by gntpet** [comment] 2023-08-09 10:07
hey @freddydk , 

Do you have any advise where to look for the issue?

**Comment by gntpet** [comment] 2023-08-10 10:24
I think I got it fixed, but have another issue :)

What I did, I completely uninstalled/unpublished all our extensions. Then, I run my script through powershell 

`Publish-BcContainerApp -bcAuthContext $bcAuthContext -environment $envName -appFile $apps -useDevEndpoint -checkAlreadyInstalled`

Everything got installed correctly. 

Then, i run CICD pipeline manually from my branch, just to test if deployment is back and working again. It did work, but it took 18 minutes to deploy, instead of normal <2min see screenshot attached.

![image](https://github.com/microsoft/AL-Go/assets/16342128/d63f472b-864d-41a5-95df-dafb55d75b51)

What I see in telemetry is that our biggest extension (core) is being reinstalled/republished for each extension. 

![image](https://github.com/microsoft/AL-Go/assets/16342128/dc43e2b4-cad3-477a-9ee3-91fd9b432a47)

Are you aware of this?

**Comment by gntpet** [comment] 2023-08-16 09:32
and the same issue is back again. 

@freddydk , could you please check what is happening here. We are getting desperate here. 

![image](https://github.com/microsoft/AL-Go/assets/16342128/00f89a64-0281-43c7-8676-9823a7f2919b)

**Comment by freddydk** [comment] 2023-08-16 21:31
Could you send me a URL where I can download a set of files so that I can try and do a repro, which I can send to the development team.
Thanks

**Comment by gntpet** [comment] 2023-08-17 08:10
Hey @freddydk, 
Thank you for coming back to me. Could you please clarify what files do you expect? App files or log files?

Yesterday, i did another change in the setup. I setup S2S auth context so the code would avoid using devendpoint & publish extension to PTE scope

![image](https://github.com/microsoft/AL-Go/assets/16342128/0187dbbf-5c00-42aa-9470-c7f2343896c7)

So now, even then deployment fails I can restart just failed job, and it resumes publishing extensions.

Nevertheless, the issue with publishing still exists. What I noticed it's very slow. As you can see it takes minutes per extension. This particular step fails after 15minutes & fails with unauthorized error. When i got to the "Deployment Status" page, i still see the extension being installed. So unauthorized error is misleading - it just timeouts after some time. 

![image](https://github.com/microsoft/AL-Go/assets/16342128/c8438029-4c0e-49d0-b02e-b0cdc3e21e70)

**Comment by freddydk** [comment] 2023-08-17 08:52
App Files - then I will try to setup a repro.
I expect this problem to be on the server somehow.

Thanks

**Comment by freddydk** [comment] 2023-08-21 10:06
You don't have to share the apps in public, you can share them with me in an email to freddyk at microsoft dot com.
If that isn't possible, you will have to create a support case with Microsoft with the same complain and see if they can do anything without a repro scenario.
Thanks

**Comment by MUR-SDP** [comment] 2024-06-27 09:43
Hi Freddy and team...

I am experiencing exactly this issue...

Error: Deploying to QA failed.  Exception calling "GetResult" with "0" argument(s): "An error occurred while sending the request."
Error: Process completed with exit code 1.

Any advice?

**Comment by freddydk** [comment] 2024-06-28 05:28
@MUR-SDP - Please create a new issue with full log (and a description of what happens).
I do believe that the root cause of this issue (expiring accesstokens) was fixed on December 1st in ContainerHelper.

**Closed by freddydk** 2024-06-28 05:28 UTC
