### ISSUE TITLE
Digital Signatures Tab not visible on app file after code signing

### ISSUE THREAD

**Issue by louagej** [microsoft/AL-Go#946] opened 2024-02-21 16:58 UTC
Hi,

I was able to setup the Azure Key Vault and run the CICD workflow.

In the log of the workflow, there is mentioned that the signing was successful:

```workflow
info: AzureSignTool.SignCommand[0]
      => File: D:\a\GTM-BC-9AFinanceBE\GTM-BC-9AFinanceBE\.buildartifacts\Apps\9altitudes_Finance BE_23.3.45.0.app
      Signing file.
info: AzureSignTool.SignCommand[0]
      => File: D:\a\GTM-BC-9AFinanceBE\GTM-BC-9AFinanceBE\.buildartifacts\Apps\9altitudes_Finance BE_23.3.45.0.app
      Signing completed successfully.
info: AzureSignTool.SignCommand[0]
      Successful operations: 1
info: AzureSignTool.SignCommand[0]
      Failed operations: 0
```

But on the properties of the file, the Digital Signatures Tab is not visible.
![image](https://github.com/microsoft/AL-Go/assets/7229592/53951363-fc58-4a3b-ad2d-214c14adc40a)

**Comment by freddydk** [comment] 2024-02-22 08:14
Looks like a duplicate of #934

**Closed** 2024-02-22 08:14 UTC
Labels: duplicate

**Comment by louagej** [comment] 2024-02-22 08:36
Hi Freddy,

Sorry to react on a closed issue, but based on the log file, the NavSip dll was installed and registered.

```log
Import from C:\ProgramData\BcContainerHelper\6.0.6\BcContainerHelper\BcContainerHelper.ps1
BcContainerHelper version 6.0.6
Ignoring unchanged config setting useCompilerFolder
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Running on PowerShell 7
Install AzureSignTool
  Skipping NuGet package signature verification.
Signing files:
- D:\a\GTM-BC-9AFinanceBE\GTM-BC-9AFinanceBE\.buildartifacts\Apps\9altitudes_Finance BE_23.3.45.0.app
Register NavSip
  Downloading artifact /sandbox/23.4.1[56](https://github.com/9altitudes/GTM-BC-9AFinanceBE/actions/runs/7992248619/job/21825386613#step:9:58)43.16451/core
  Downloading C:\Users\runneradmin\AppData\Local\Temp\d7a15fc4-ca28-4653-b4fb-7a1e[59](https://github.com/9altitudes/GTM-BC-9AFinanceBE/actions/runs/7992248619/job/21825386613#step:9:61)8cbde9.zip
  Downloading using HttpClient
  Unpacking artifact to tmp folder using 7zip
  Downloaded artifacts to C:\Users\runneradmin\AppData\Local\Temp\5sgm0p5e.kp1
  Found navsip at C:\Users\runneradmin\AppData\Local\Temp\5sgm0p5e.kp1\sandbox\23.4.15[64](https://github.com/9altitudes/GTM-BC-9AFinanceBE/actions/runs/7992248619/job/21825386613#step:9:67)3.16451\core\NavSip.dll
  Copied navsip to C:\Windows\System32\navsip.dll
  Unregistering dll C:\Windows\System32\navsip.dll
  Registering dll C:\Windows\System32\navsip.dll
info: AzureSignTool.SignCommand[0]
      => File: D:\a\GTM-BC-9AFinanceBE\GTM-BC-9AFinanceBE\.buildartifacts\Apps\9altitudes_Finance BE_23.3.45.0.app
      Signing file.
info: AzureSignTool.SignCommand[0]
      => File: D:\a\GTM-BC-9AFinanceBE\GTM-BC-9AFinanceBE\.buildartifacts\Apps\9altitudes_Finance BE_23.3.45.0.app
      Signing completed successfully.
info: AzureSignTool.SignCommand[0]
      Successful operations: 1
info: AzureSignTool.SignCommand[0]
      Failed operations: 0
```
