### ISSUE TITLE
Issue with param bccontainerhelperversion & different helper versions loaded

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#513] opened 2023-05-08 12:17 UTC
Hey @freddydk , 

I have discovered the issue with BcCotainerHelperVersion parameter. It seems that AL-GO is totally ignoring. I tried to use older version due to the issue #467 and noticed that it is ignored completely.
 
![image](https://user-images.githubusercontent.com/16342128/236819926-e95812f2-85d8-4e06-8acd-e667157c4e98.png)

If I check logs, i see that settings is passing 4.0.10 correctly, but it still load 4.0.16
![image](https://user-images.githubusercontent.com/16342128/236820354-b08411b9-ad32-4616-a8ae-3eedb44b85a2.png)

and in some cases it loads 5.0.0

![image](https://user-images.githubusercontent.com/16342128/236820609-6da367ad-da5a-4c63-89e5-08f208afe874.png)

Here's is the summary, which version is loaded for which step
4.0.16: ReadSettings,  RunPipeline, CreatingContainer, AnalyzeTestResults
5.0.0: ReadSecrets

Best Regards, 
Gintautas

**Comment by freddydk** [comment] 2023-05-08 14:09
Yeah, the problem is really that AL-Go has a dependency on a specific version of BcContainerHelper - and allowing people to use a different version might actually give more problems than we want.
preview version of AL-Go will use preview version of ContainerHelper and latest will use latest.
ContainerHelper 5.0.0 was shipped saturday with the fix for the above problem.
The other mechanism we could have used would haven been to shift to use AL-Go preview.

**Comment by freddydk** [comment] 2023-05-09 03:57
BTW - on the 5.0.0 vs. 4.0.16 is probably because the CDN isn't fully updated yet - should be 5.0.0 now.

**Comment by gntpet** [comment] 2023-05-09 12:01
> We should probably allow people to specify to use containerhelper preview in AL-Go latest, that way should always be compatible - but not going backwards.

The only reason, why i would see a need to control bccontainerhelper version, is to prevent changes to the build code. What happens now, AL-GO system update is controlled process. I can test in within separate branch. On the other side, bccontainerhelper version can change anytime, and we have no control in that, thus leaving with failing build pipelines, without possibility revert back to previous version. Would it be idea to link certain bccontainerhelper version with AL-GO? So, at least it would be tested altogether with AL-GO updates?

> BTW - on the 5.0.0 vs. 4.0.16 is probably because the CDN isn't fully updated yet - should be 5.0.0 now.

Just run a job now, and still see two different BcCotainerHelper versions used.

**Comment by freddydk** [comment] 2023-05-15 19:07
Fixed in v3.1

**Closed by freddydk** 2023-05-15 19:07 UTC
Labels: enhancement, Fix Ready, In Progress, Shipped
