### ISSUE TITLE
Is it possible to avoid the PR build?

### ISSUE THREAD

**Issue by spookymattress** [microsoft/AL-Go#529] opened 2023-05-11 09:45 UTC
New to AL-go but when I make a feature branch, and the merge into main, it will create both a PR build and build. 

Can I avoid the PR build?

**Comment by freddydk** [comment] 2023-05-11 09:57
The PR build is done in order to make sure that the main branch isn't broken and is valuable during code review etc.
If you don't want it, you can create a repo setting (.github/AL-Go-Settings.json) called CICDPullRequestBranches. Default is:

```
"CICDPullRequestBranches": [ "main" ]
```

Not sure whether it can be empty - or you need to specify a dummy branch.
After changing the setting, you need to run update AL-Go System Files.

**Comment by spookymattress** [comment] 2023-05-11 10:01
The main reason is to speed up build time, so I dont't have two build running right after each other. And I'll take the risk that main cannot build then.

> There is an argument to be made that you might not need the build on main because the code was build in the PR.
> 
Well, you might not, but it could be that others have commit code that breaks your code

**Comment by jonaswre** [comment] 2023-05-11 10:16
Speedup build times is always the reason. 
Are you on a github hosted agent or selfhosted runner? 
We had the biggest improvement moving to a selfhosted runner. We run both builds and its still faster then a single build on a github hosted runner. And @freddydk is always improving build times. 


> > There is an argument to be made that you might not need the build on main because the code was build in the PR.

> Well, you might not, but it could be that others have commit code that breaks your code

Not if you block direct commits. Then all code changes need to go through a pr.

**Comment by freddydk** [comment] 2023-05-11 10:18
On the build times - we are adding some changes to that, building without containers and building on linux can make the build time go down dramatically - we will ship these things over the next months.

**Comment by jonaswre** [comment] 2023-05-11 10:24
> On the build times - we are adding some changes to that, building without containers and building on linux can make the build time go down dramatically - we will ship these things over the next months.

Build times on linux would make it not only fast but also cheaper.  Github charges double the rates for windows minutes. And Azure VMs are also much more expensive with windows.

**Comment by spookymattress** [comment] 2023-05-11 11:29
> Speedup build times is always the reason. Are you on a github hosted agent or selfhosted runner? We had the biggest improvement moving to a selfhosted runner. We run both builds and its still faster then a single build on a github hosted runner. And @freddydk is always improving build times.
> 
I'll just experimenting with AL-Go - we normally use devops.

I'm trying to setup a self-hosted runner, but ran into problems. But I need to look into that.

**Comment by freddydk** [comment] 2023-05-11 11:39
https://aka.ms/getbuildagent is by far the easiest way to setup self-hosted runners.

**Comment by spookymattress** [comment] 2023-05-11 11:43
> https://aka.ms/getbuildagent is by far the easiest way to setup self-hosted runners.

Sure, did that, but the runner is not fetching the build request when setup in the organisation - only when I do it in the repo

**Comment by freddydk** [comment] 2023-05-11 11:46
You need to make a AL-Go setting called "GitHubRunner": "selfhosted" in order for AL-Go to use it for builds

**Comment by freddydk** [comment] 2023-05-11 11:47
If you also want to use self hosted runners for non-build jobs, set "runs-on" to "selfhosted" as well and run Update AL-Go System Files.
You can also have GitHubRunner set to selfhosted and runs-on to ubuntu-latest to run non-build jobs on Linux.

**Comment by spookymattress** [comment] 2023-05-11 12:00
> You need to make a AL-Go setting called "GitHubRunner": "selfhosted" in order for AL-Go to use it for builds

I think you mean "GitHubRunner": "self-hosted"? Right?

**Comment by jonaswre** [comment] 2023-05-11 12:06
> > You need to make a AL-Go setting called "GitHubRunner": "selfhosted" in order for AL-Go to use it for builds
> 
> I think you mean "GitHubRunner": "self-hosted"? Right?

You can check the docs. https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/al-go/algo-setup-github-runner-performance

**Comment by freddydk** [comment] 2023-05-11 14:52
> > You need to make a AL-Go setting called "GitHubRunner": "selfhosted" in order for AL-Go to use it for builds
> 
> I think you mean "GitHubRunner": "self-hosted"? Right?

Yes, I think you are right.

**Comment by freddydk** [comment] 2023-05-13 05:08
On the original question, I can confirm that it is possible to disable the PR build by adding this:

```
"CICDPullRequestBranches": [ "main" ]
```

to your repo settings file (.github/AL-Go-Settings.json)

It is however not recommended.

**Closed** 2023-05-13 05:08 UTC
Labels: question, Fix Ready

**Comment by jonaswre** [comment] 2023-05-25 09:09
Yes for some of these changes its nessary to run Update System Files because it needs to make changes in the yaml files.

Which actually need to be written.
