### ISSUE TITLE
Old containers left on self-hosted runner

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL-Go#459] opened 2023-04-03 10:19 UTC
One of our self-hosted runners ran out of disk space (the disk is 256GB).
The bcch cache is about 10GB holding artifacts from the past three days, so no problem there.
But looking at containers I see multiple old containers that I do not understand, see list below. 
Deleting them freed up 100GB. I wonder if there is a bug where containers do not get cleaned up?
The other runner had two such containers from 6 weeks ago.

```
PS C:\Users\vmadmin> docker ps -a
CONTAINER ID   IMAGE          COMMAND                  CREATED             STATUS                         PORTS     NAMES
57f3604fdc17   ef673db7c09f   "powershell -Command…"   About an hour ago   Exited (0) About an hour ago             kind_mendel
098b5d476f95   1487192b5e28   "powershell -Command…"   2 weeks ago         Exited (0) 2 weeks ago                   eager_chatelet
9fc7720341b2   37a83ad5ee8b   "powershell -Command…"   2 weeks ago         Exited (0) 2 weeks ago                   stoic_hawking
b0a27497a0df   24e9892dca6f   "powershell -Command…"   2 weeks ago         Exited (0) 2 weeks ago                   friendly_shockley
f3a223714285   33980752eb26   "powershell -Command…"   6 weeks ago         Exited (0) 6 weeks ago                   heuristic_solomon
b3d2cce3ee3a   84c653cf3e88   "powershell -Command…"   6 weeks ago         Exited (0) 6 weeks ago                   focused_sutherland
b208ca4352d3   573b0db8a30b   "powershell -Command…"   6 weeks ago         Exited (0) 6 weeks ago                   festive_mclaren
f94dbcc794cb   232da1925216   "powershell -Command…"   6 weeks ago         Exited (0) 6 weeks ago                   loving_thompson
6f9b6005442d   d87a850fdf7d   "powershell -Command…"   6 weeks ago         Exited (0) 6 weeks ago                   awesome_feistel
cc14f43e875c   0e44832d278e   "powershell -Command…"   6 weeks ago         Exited (0) 6 weeks ago                   romantic_khorana
823231e029d0   c9df5d438d39   "powershell -Command…"   6 weeks ago         Exited (0) 6 weeks ago                   heuristic_poincare
38b7af11f16a   8590ae03e6ad   "powershell -Command…"   6 weeks ago         Exited (0) 6 weeks ago                   wizardly_hamilton
faa196930e27   a10d14f5fbf0   "powershell -Command…"   6 weeks ago         Exited (0) 6 weeks ago                   nice_banzai
9942b64382fe   99f4c584e9e0   "powershell -Command…"   6 weeks ago         Exited (0) 6 weeks ago                   beautiful_lewin
e8f864b0e89e   98d4d2f6ab4e   "powershell -Command…"   6 weeks ago         Exited (0) 6 weeks ago                   serene_nightingale
1b0f064a8f5e   3dded10af40f   "powershell -Command…"   6 weeks ago         Exited (0) 6 weeks ago                   dreamy_proskuriakova
2d093823cd8a   35933d3e427a   "powershell -Command…"   7 weeks ago         Exited (0) 7 weeks ago                   loving_cray
```

**Comment by freddydk** [comment] 2023-04-03 10:24
These names are typically from attempts to create an image, which has gone wrong.
Not sure if/what we can do about these...
Will investigate when I have time.

**Comment by janlehmkuhl** [comment] 2023-04-03 10:50
Hey @AskeHolst, perhaps it could help you, until Freddy takes a closer look, to run a PowerShell script, for example, once a week using the Windows "Task Scheduler" that clears the ContainerHelperCache and cleans up Docker.

`$hostname = hostname`
`Get-Service -Name actions.runner.ctmcomputer.$hostname-* | ForEach-Object { Stop-Service $_.Name }`
`Install-Module BcContainerHelper -Force`
`Flush-ContainerHelperCache`
`docker system prune -a --force`
`Restart-Computer -Force`

This script finds and stops all GitHub Agent services, updates the BCContainerHelper, and then clears the ContainerHelperCache and completely cleans up Docker. Subsequently, the computer is also restarted, which restarts the Agent services for us. It may or may not help you, but you can customize the scripts according to your needs. Please note that this script should ideally not be run every day, as the initial, first loading of an image can take a bit longer.

**Comment by freddydk** [comment] 2023-04-04 16:54
@AskeHolst - if you look back in time, where these containers are from - can you then see any pattern? like were there a number of builds failing during container creation?
Thanks

**Comment by AskeHolst** [comment] 2023-04-04 18:04
@freddydk This has happened when disk space got low. Then the container creation failed, but also the removal. See example below. 

```

      _____                _   _                               _        _                 
    / ____|              | | (_)                             | |      (_)                
   | |     _ __ ___  __ _| |_ _ _ __   __ _    ___ ___  _ __ | |_ __ _ _ _ __   ___ _ __ 
   | |    | '__/ _ \/ _` | __| | '_ \ / _` |  / __/ _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
   | |____| | |  __/ (_| | |_| | | | | (_| | | (__ (_) | | | | |_ (_| | | | | |  __/ |   
    \_____|_|  \___|\__,_|\__|_|_| |_|\__, |  \___\___/|_| |_|\__\__,_|_|_| |_|\___|_|   
                                       __/ |                                             
                                      |___/                                              
  
  BcContainerHelper is version 4.0.14
  BcContainerHelper is running as administrator
  HyperV is Disabled
  UsePsSession is True
  Host is Microsoft Windows Server 2022 Datacenter - 10.0.20348.1487
  Docker Client Version is 20.10.21
  Docker Server Version is 20.10.21
  Removing Desktop shortcuts
  Fetching all docker images
  Fetching all docker volumes
  ArtifactUrl and ImageName specified
  Waiting for other process building image my:sandbox-21.4.52563.53229-gb-mt
  Other process completed building
  Fetching all docker images
  Building multitenant image my:sandbox-21.4.52563.53229-gb-mt based on mcr.microsoft.com/businesscentral:10.0.20348.1487 with https://bcartifacts.azureedge.net/sandbox/21.4.52563.53229/gb
  Pulling latest image mcr.microsoft.com/businesscentral:10.0.20348.1487
  10.0.20348.1487: Pulling from businesscentral
  Digest: sha256:c4b4a98fb5ebecb8dc95a1c9ba9f6afbb98c103ff167ea21bc254044e6b08a16
  Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.20348.1487
  mcr.microsoft.com/businesscentral:10.0.20348.1487
  Generic Tag: 1.0.2.14
  Container OS Version: 10.0.20348.1487 (ltsc2022)
  Host OS Version: 10.0.20348.1487 (ltsc2022)
  Using process isolation
  Using license file https://***.file.core.windows.net/cicd/SE.bclicense
  Downloading c:\bcartifacts.cache\r0cghm4p.h2p\my\license.bclicense
  Using WebClient
  Files in c:\bcartifacts.cache\r0cghm4p.h2p\my:
  - license.bclicense
  Copying Platform Artifacts
  c:\bcartifacts.cache\sandbox\21.4.52563.53229\platform
  Copying Database
  Copying Licensefile
  Copying ConfigurationPackages
  C:\bcartifacts.cache\sandbox\21.4.52563.53229\gb\ConfigurationPackages
  Copying Extensions
  C:\bcartifacts.cache\sandbox\21.4.52563.53229\gb\Extensions
  Copying Applications.GB
  C:\bcartifacts.cache\sandbox\21.4.52563.53229\gb\Applications.GB
  c:\bcartifacts.cache\r0cghm4p.h2p
  Sending build context to Docker daemon  2.209GB
  
  Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.20348.1487
   ---> 113b079c6f47
  Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=Y artifactUrl=https://bcartifacts.azureedge.net/sandbox/21.4.52563.53229/gb filesOnly=False
   ---> Running in 6fdf9a63d646
  Removing intermediate container 6fdf9a63d646
   ---> eaa7ecc[393](https://github.com/[REDACTED]/[REDACTED]/actions/runs/4478074007/jobs/7870418022#step:10:401)49
  Step 3/6 : COPY my /run/
   ---> ff61132296f7
  Step 4/6 : COPY NAVDVD /NAVDVD/
   ---> 0e44832d278e
  Step 5/6 : RUN \Run\start.ps1 -installOnly -multitenant
   ---> Running in cc14f43e875c
  c:\run\my folder doesn't exist, creating it
  Using installer from C:\Run\210-new
  Installing Business Central
  Installing from DVD
  Starting Local SQL Server
  Starting Internet Information Server
  Copying Service Tier Files
  C:\NAVDVD\ServiceTier\Program Files
  C:\NAVDVD\ServiceTier\System64Folder
  Copying PowerShell Scripts
  C:\NAVDVD\WindowsPowerShellScripts\Cloud\NAVAdministration
  C:\NAVDVD\WindowsPowerShellScripts\WebSearch
  Copying Web Client Files
  C:\NAVDVD\WebClient\Microsoft Dynamics NAV
  Copying ModernDev Files
  C:\NAVDVD
  C:\NAVDVD\ModernDev\program files\Microsoft Dynamics NAV
  Copying additional files
  Copying ConfigurationPackages
  C:\NAVDVD\ConfigurationPackages
  Copying Test Assemblies
  C:\NAVDVD\Test Assemblies
  Copying Extensions
  C:\NAVDVD\Extensions
  Copying Applications
  C:\NAVDVD\Applications
  Copying Applications.GB
  C:\NAVDVD\Applications.GB
  Copying dependencies
  Copying ReportBuilder
  Importing PowerShell Modules
  Restoring CRONUS Demo Database
  Setting CompatibilityLevel for tenant on localhost\SQLEXPRESS
  Exporting Application to CRONUS
  Removing Application from tenant
  Modifying Business Central Service Tier Config File for Docker
  Creating Business Central Service Tier
  Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
  Starting Business Central Service Tier
  Importing CRONUS license file
  Copying Database on localhost\SQLEXPRESS from tenant to default
  Taking database tenant offline
  Copying database files
  Attaching files as new Database default
  Putting database tenant back online
  Mounting tenant database
  Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
  Sync'ing Tenant
  Tenant is Operational
  Stopping Business Central Service Tier
  Installation took 257 seconds
  Installation complete
  re-exec error: exit status 1: output: hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)
  New-Bcimage Telemetry Correlation Id: dc5c3e17-233d-47f9-95a8-df8678e9e2fe
  New-BcContainer Telemetry Correlation Id: ed34d713-fcfb-451d-8895-7d6617fceb6b
Removing container
  Get Event Log from container
  Getting event log for bc[418](https://github.com/[REDACTED]/[REDACTED]/actions/runs/4478074007/jobs/7870418022#step:10:426)2844805
  Error: No such object: bc4182844805
  Removing Desktop shortcuts
Run-AlPipeline Telemetry Correlation Id: bdb74692-28d3-4538-97db-8575fe44690e
Error: RunPipeline action failed. Error: Docker Build failed with exit code 1 Stacktrace: at New-BcImage, C:\Windows\TEMP\9d913025-8177-4d75-87c1-dc20f802d948\BcContainerHelper\ContainerHandling\New-NavImage.ps1: line 671 at New-BcContainer, C:\Windows\TEMP\9d913025-8177-4d75-87c1-dc20f802d948\BcContainerHelper\ContainerHandling\New-NavContainer.ps1: line 605 at <ScriptBlock>, C:\Windows\TEMP\9d913025-8177-4d75-87c1-dc20f802d948\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 653 at <ScriptBlock>, C:\Windows\TEMP\9d913025-8177-4d75-87c1-dc20f802d948\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 861 at <ScriptBlock>, C:\Windows\TEMP\9d913025-8177-4d75-87c1-dc20f802d948\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 804 at <ScriptBlock>, C:\Windows\TEMP\9d913025-8177-4d75-87c1-dc20f802d948\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 787 at Run-AlPipeline, C:\Windows\TEMP\9d913025-8177-4d75-87c1-dc20f802d948\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 749 at <ScriptBlock>, C:\2\_work\_actions\microsoft\AL-Go-Actions\v2.4\RunPipeline\RunPipeline.ps1: line 365 at <ScriptBlock>, C:\2\_work\_temp\d4efbb6b-7d03-40ca-883c-d9b8efcba0b2.ps1: line 2 at <ScriptBlock>, <No file>: line 1
AL-Go action ran: RunPipeline Telemetry Correlation Id: bbd7bf5f-6a8b-[427](https://github.com/[REDACTED]/[REDACTED]/actions/runs/4478074007/jobs/7870418022#step:10:435)a-a73c-c1893dbbb06f
Removing BcContainerHelper
Error: Process completed with exit code 1.
```

Additional question, what are all the < none > images used for?
```
PS C:\Users\vmadmin> docker images -a
REPOSITORY                          TAG                              IMAGE ID       CREATED        SIZE
my                                  sandbox-22.0.54157.54994-se-mt   c71bca0b18c5   4 hours ago    14GB
<none>                              <none>                           0d056ded8fa8   4 hours ago    14GB
<none>                              <none>                           d5e72b87b1eb   4 hours ago    9.6GB
<none>                              <none>                           7cb8b8981521   4 hours ago    7.12GB
<none>                              <none>                           9354dc34eaea   4 hours ago    7.12GB
my                                  sandbox-22.0.54157.54994-gb-mt   99587565abed   8 hours ago    14.1GB
<none>                              <none>                           e651b050ec74   8 hours ago    14.1GB
<none>                              <none>                           dd22ca8e2035   8 hours ago    9.6GB
<none>                              <none>                           1d7e21cec536   8 hours ago    7.12GB
<none>                              <none>                           0e7f8d3745d7   8 hours ago    7.12GB
my                                  sandbox-22.0.54157.54941-gb-mt   c7b47323f346   31 hours ago   14GB
<none>                              <none>                           91a400426342   31 hours ago   14GB
<none>                              <none>                           45d40f05c1c3   31 hours ago   9.61GB
<none>                              <none>                           488329cd1279   31 hours ago   7.12GB
<none>                              <none>                           d8d1ccfc3cba   31 hours ago   7.12GB
<none>                              <none>                           62cb7df4ae81   31 hours ago   14GB
<none>                              <none>                           03e47f7c96d3   31 hours ago   9.61GB
<none>                              <none>                           d35042b337ed   31 hours ago   7.12GB
<none>                              <none>                           8719779c71ad   31 hours ago   7.12GB
my                                  sandbox-22.0.54157.54941-us-mt   09c25c814d42   31 hours ago   14GB
<none>                              <none>                           7cb41a06b26b   31 hours ago   14GB
<none>                              <none>                           a253a5947840   31 hours ago   9.62GB
<none>                              <none>                           15f049e48f80   31 hours ago   7.12GB
<none>                              <none>                           0d5b082ae139   31 hours ago   7.12GB
my                                  sandbox-21.5.53619.54930-se-mt   9f920afb8672   33 hours ago   13.3GB
<none>                              <none>                           f7a583920a43   33 hours ago   13.3GB
my                                  sandbox-21.5.53619.54930-w1-mt   33ece906ebcf   33 hours ago   12.8GB
<none>                              <none>                           1ad42a27bf1a   33 hours ago   12.8GB
<none>                              <none>                           eb2c1881f021   33 hours ago   9.32GB
<none>                              <none>                           96d1b034ca82   33 hours ago   7.12GB
<none>                              <none>                           738d11682cff   33 hours ago   7.12GB
<none>                              <none>                           7d88e062a225   33 hours ago   9.15GB
<none>                              <none>                           5730caeb92f3   33 hours ago   7.12GB
<none>                              <none>                           4700b4d4782f   33 hours ago   7.12GB
my                                  sandbox-21.5.53619.54930-gb-mt   90c0eaef0e59   33 hours ago   13.4GB
<none>                              <none>                           bd44193434d2   33 hours ago   13.4GB
<none>                              <none>                           2bc28ead79f6   33 hours ago   9.33GB
<none>                              <none>                           884ecc06156b   34 hours ago   7.12GB
<none>                              <none>                           db347a8b1e47   34 hours ago   7.12GB
mcr.microsoft.com/businesscentral   10.0.20348.1607                  e90591a0794a   2 weeks ago    7.12GB
```

**Comment by freddydk** [comment] 2023-07-06 05:02
Sorry for the late reply.
The <none>:<none> images are images, which no longer are referenced (docker calls them dangling images).
They are from failed attempts to build images.
AL-Go should be running regular cleanup of images and stuff that hasn't ben touched in 3 days (controlled by the cacheKeepDays setting). Is this not what you are seeing?

**Comment by freddydk** [comment] 2023-07-06 05:11
One thing, which might be the cause of this is, that the containerhelper flush command doesn't cleanup dangling images.
The reason for this is, that another agent might be building an image at the same time, and this would be removed.
You could create a startup task on the machine which runs:
![image](https://github.com/microsoft/AL-Go/assets/10775043/5cb6069a-2412-49c5-abee-d4b01155383b)

and then reboot the machines nightly at midnight or like.

**Comment by freddydk** [comment] 2023-07-06 05:17
having seen this help now - I will add a docker image prune --filter until="cachekeepdays timestamp" to containerhelper.
That should take care of this.

**Comment by freddydk** [comment] 2023-07-06 06:11
https://github.com/microsoft/navcontainerhelper/pull/3107

will be in next prerelease of ContainerHelper

**Closed** 2023-07-06 06:11 UTC
Labels: enhancement, Fix Ready, Unrelated to AL-Go
