### ISSUE TITLE
[Bug]: Publish to AppSource fails

### ISSUE THREAD

**Issue by dsaveyn** [microsoft/AL-Go#1238] opened 2024-10-03 09:20 UTC
### AL-Go version

5.3

### Describe the issue

The Deliver to AppSource step of the Publish to AppSource action fails since today with the following error: 

`Error: Unexpected error when running action. Error Message: Command /home/runner/.bccontainerhelper/alLanguageExtension/14.0.1161190/extension/bin/linux/altool not found, you might need to install that command., StackTrace: at CmdDo, /home/runner/.BcContainerHelper/6.0.24/BcContainerHelper/HelperFunctions.ps1: line 129 <- at RunAlTool, /home/runner/.BcContainerHelper/6.0.24/BcContainerHelper/HelperFunctions.ps1: line 1283 <- at Get-AppJsonFromAppFile, /home/runner/.BcContainerHelper/6.0.24/BcContainerHelper/AppHandling/Get-AppJsonFromAppFile.ps1: line 15 <- at New-AppSourceSubmission, /home/runner/.BcContainerHelper/6.0.24/BcContainerHelper/AppSource/New-AppSourceSubmission.ps1: line 102 <- at <ScriptBlock>, /home/runner/work/_actions/microsoft/AL-Go-Actions/v5.3/Deliver/Deliver.ps1: line 478 <- at <ScriptBlock>, /home/runner/work/_temp/d7b2c327-524b-4d0c-b514-cdc4676d448f.ps1: line 3 <- at <ScriptBlock>, /home/runner/work/_actions/microsoft/AL-Go-Actions/v5.3/Invoke-AlGoAction.ps1: line 17 <- at <ScriptBlock>, /home/runner/work/_temp/d7b2c327-524b-4d0c-b514-cdc4676d448f.ps1: line 2 <- at <ScriptBlock>, <No file>: line 1`

### Expected behavior

This should work as before.

### Steps to reproduce

- Run the "Create a Release" action
- Run the "Publish to AppSource" action to publish the release

### Additional context (logs, screenshots, etc.)

![image](https://github.com/user-attachments/assets/2a8f2fa6-cf61-4823-ac20-208bc7a4bab6)
[job-logs.txt](https://github.com/user-attachments/files/17242027/job-logs.txt)

**Comment by dsaveyn** [comment] 2024-10-03 09:39
FYI: We have configured ubuntu-latest as the runner for non-build jobs.

**Comment by freddydk** [comment] 2024-10-03 11:26
The reason for this is that the latest AL Language Extension has introduced a bug on linux.
I am working on a temp fix (should be in tomorrow) and the ModernDev team also working on a fix for this.

**Comment by fvet** [comment] 2024-10-06 18:13
@freddydk  Thanks for the quick fix. I can confirm the 'Publish to AppSource' action is working again on ALGo!

**Closed** 2024-10-17 04:33 UTC
Labels: bug, Fix Ready, Unrelated to AL-Go
