### ISSUE TITLE
Best practice for common org settings

### ISSUE THREAD

**Issue by AskeHolst** [microsoft/AL-Go#359] opened 2023-01-16 19:23 UTC
We have a few settings we add in every new repo. Things like "enableCodeCop":  true and "gitHubRunner":  "self-hosted". 

Currently, we are making the changes manually in every new repo, but is there a smarter way?

I thought of forking Al-Go, creating new template repos, but then there is one more thing to maintain and the risk of really breaking something.

**Comment by AskeHolst** [comment] 2023-01-16 21:57
Great, looking forward to that. Perfectly timed question then.

But please not AlGoSettings, we already have enough problems with Al-Go-Settings and Al-Go/settings. "did you update Al-Go-Settings? Yes I updated Al-Go/settings...". 🤯

To me there are: project-settings, repo-settings, and soon org-settings. Maybe the naming could reflect that? Small thing, but we have stumbled over frequently.

**Comment by freddydk** [comment] 2023-01-16 21:59
ALGoOrgSettings maybe then - it needs to be something that doesn't conflict with other things (hence the ALGo)

**Comment by freddydk** [comment] 2023-01-16 22:21
With the org settings you would be able to create an org setting called AZURE_CREDENTIALSSECRETNAME = 'somesecretname' to use a different secret for all repos.

**Comment by AskeHolst** [comment] 2023-01-16 22:37
Yes, the org settings will make a lot possible. It is just a lot of indirection. You have built something really powerful, and I'm impressed with the speed of progress and your attention to issues. For day to day operations, it is fantastic. 
The learning curve when it comes to setting it up initially, even with prior GH experience, is tough when it comes to figuring out the layers of settings/secrets in Al-Go-Settings, Al-Go/settings, repo-secrets, org-secrets and key-vault. The HOL slides and videos did help a lot though. 
I just discovered the roadmap - great stuff - you should link to that in the readme.md.
Sorry for the side track, I'm just becoming a bit invested in this - in a good way 😀

**Comment by freddydk** [comment] 2023-01-17 07:13
Thanks
You are right, that there are a TON of possibilities, but for a lot of simple repositories, it is actually really simple.
I am looking for ways to make the learning curve simpler.

> I just discovered the roadmap - great stuff - you should link to that in the readme.md.
Will do:-)

**Comment by freddydk** [comment] 2023-01-21 06:44
Will close this as a duplicate of https://github.com/microsoft/AL-Go/issues/372 (converted to issue from the roadmap)

**Closed** 2023-01-21 06:44 UTC
Labels: duplicate

**Comment by freddydk** [comment] 2023-01-26 07:02
Org and Repo variables are now included in the settings matrix.
