### ISSUE TITLE
PTE with AppSource App Dependencies - using symbols

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#196] opened 2022-09-08 21:14 UTC
Since we are creating some PTEs that have dependencies to AppSource apps, I figured, the best way is to connect to the Sandbox and download the symbols for all the AppSource apps. Those symbols I then have uploaded to a Storage Blob and reference the URLs in the "installApps" section of the settings.json.

When I run the pipeline, it then properly downloads and installs the apps into the container (according to the log), but when the app is compiled, it errors out with the messages that the AppSource app objects are not found (the ones that are extended, etc.).

Can I not use symbols or would they have to be defined differently?

**Comment by pzentner** [comment] 2022-09-26 19:43
I wanted to provide an update here. What I have found is that it works when the symbols are from an app that includes source code, but not when that is not included. 

What I can do manually in a docker container is:
1. install the symbols
2. install the app
3. compile the app

But the same fails in the pipeline, it seems. It could be that the installation of the apps is handled with "installing an app" and not "installing symbols package type", because that's what I need to do in the first step when doing it manually.

**Comment by freddydk** [comment] 2022-10-22 16:18
Duplicate of #77

**Closed by freddydk** 2022-10-22 16:18 UTC
Labels: duplicate
