### ISSUE TITLE
AL-GO build fails for multi-project repository when there's nothing to build

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#186] opened 2022-09-02 12:29 UTC
Hey Guys, 

I did setup multi-project repository which is very similiar to [Contoso-App2](https://github.com/BusinessCentralApps/Contoso-App2/).
There, I did single change by modifying only al.workspace file. That's the only change in my commit. Thus, Al-GOshould not build any of the apps, since there're no changes. 

But instead build fails with an error:
`Error when evaluating 'strategy' for job 'Build'. .github/workflows/CICD.yaml (Line: 75, Col: 18): Error parsing fromJson,.github/workflows/CICD.yaml (Line: 75, Col: 18): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/CICD.yaml (Line: 75, Col: 18): Unexpected type of value '', expected type: Sequence.`

I guess that generated yaml file is corrupt. It's a minor issue for me, but perhaps you want to take a look at it. 
![image](https://user-images.githubusercontent.com/16342128/188142636-9101c697-f21e-4e3b-bea1-96fbf5a09c1b.png)

**Comment by freddydk** [comment] 2022-09-03 02:42
Yeah, the issue is, that I calculate a matrix containing the jobs to build - and that matrix is empty.
It should have an if statement to just ignore this, will have a look

**Comment by freddydk** [comment] 2022-09-09 14:08
Fixed in the latest preview

**Comment by freddydk** [comment] 2022-09-25 09:01
Shipped in v2.0

**Closed by freddydk** 2022-09-25 09:01 UTC
Labels: bug, Fix Ready, Ships in a future version
