### ISSUE TITLE
Unable to Update AL-Go System files / Create a release

### ISSUE THREAD

**Issue by curateideas** [microsoft/AL-Go#593] opened 2023-07-05 10:19 UTC
I encounter an issue during actions "Update AL-Go System Files" and "Create a release" (which also runs "Check for Updates".

Error: "CheckForUpdates action failed. Error: The property 'unusedALGoSystemFiles' cannot be found on this object. Verify that the property exists."

Runner is self-hosted.

Only one repo is affected.

AL-Version is 3.0

Settings doesn't contain the mentioned "unusedALGoSystemFiles"

Run microsoft/AL-Go-Actions/CheckForUpdates@v3.0
  with:
    shell: powershell
    parentTelemetryScopeJson: 7b[2](https://github.com/ctmcomputer/Sinnack-Business-Central/actions/runs/5462976688/jobs/9943098037#step:4:2)2506172616d657465727[3](https://github.com/ctmcomputer/Sinnack-Business-Central/actions/runs/5462976688/jobs/9943098037#step:4:3)223a7b7d2c22[4](https://github.com/ctmcomputer/Sinnack-Business-Central/actions/runs/5462976688/jobs/9943098037#step:4:4)[5](https://github.com/ctmcomputer/Sinnack-Business-Central/actions/runs/5462976688/jobs/9943098037#step:4:5)6d6974746564223a66616c73652c22436f7272656c6174696f6e4964223a2262666530373565632d373361612d343331642d386432362d386565626337323232616164222c22506172656e744964223a22222c22416c6c506172616d6574657273223a7b7d2c22546f704964223a2262666530373565632d373361612d343331642d386432362d386565626337323232616164222c224e616d65223a22414c2d476f20776f726b666c6f772072616e3a2043494344222c22537461727454696d65223a225c2f446174652831363838353531343230323130295c2f222c2250726f70657274696573223a7b226576656e744964223a22444f30303931222c226263436f6e7461696e657248656c70657256657273696f6e223a22352e302e33222c22697341646d696e6973747261746f72223a2254727565222c22737461636b5472616365223a225b5c6e2020496e697454656c656d6574727953636f70652061742054656c656d6574727948656c7065722e7073313a206c696e65203231345c6e202043726561746553636f70652061742054656c656d6574727948656c7065722e70736d313a206c696e652037315c6e2020576f726b666c6f77496e697469616c697a652e70733120617420576f726b666c6f77496e697469616c697a652e7073313a206c696e652033375c6e202032363361373934632d643137362d346462632d613837632d3864316635663033303639612e7073312061742032363361373934632d643137362d346462632d613837632d3864316635663033303639612e7073313a206c696e6520325c6e20205c7530303363536372697074426c6f636b5c7530303365206174205c75303033634e6f2066696c655c75303033655c6e5d222c22414c476f56657273696f6e223a2276332e30222c2274797065223a22505445222c2274656d706c61746555726c223a2268747470733a2f2f6769746875622e636f6d2f6d6963726f736f66742f414c2d476f2d505445406d61696e222c227265706f7369746f7279223a2263746d636f6d70757465722f53696e6e61636b2d427573696e6573732d43656e7472616c222c2272756e417474656d7074223a2231222c2272756e4e756d626572223a223436222c2272756e4964223a2235343632393736363838227d2c224576656e744964223a22444f30303931227d
    templateUrl: https://github.com/microsoft/AL-Go-PTE@main
    actor: curateideas
    token: ***
    update: N
    updateBranch: main
    directCommit: N
  env:
    workflowDepth: 1
    ALGoOrgSettings: 
    ALGoRepoSettings: 
    templateUrl: https://github.com/microsoft/AL-Go-PTE@main
    Settings: {"templateUrl":"https://github.com/microsoft/AL-Go-PTE@main"}
Run try { C:\CTMBuildAgent03-1\_work\_actions\microsoft\AL-Go-Actions\v3.0\CheckForUpdates/CheckForUpdates.ps1 -actor $ENV:_actor -token $ENV:_token -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson -templateUrl $ENV:_templateUrl -templateBranch $ENV:_templateBranch -update ($ENV:_update -eq 'Y') -updateBranch $ENV:_updateBranch -directCommit ($ENV:_directCommit -eq 'Y') } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
  try { C:\CTMBuildAgent03-1\_work\_actions\microsoft\AL-Go-Actions\v3.0\CheckForUpdates/CheckForUpdates.ps1 -actor $ENV:_actor -token $ENV:_token -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson -templateUrl $ENV:_templateUrl -templateBranch $ENV:_templateBranch -update ($ENV:_update -eq 'Y') -updateBranch $ENV:_updateBranch -directCommit ($ENV:_directCommit -eq 'Y') } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
  shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.EXE -command ". '{0}'"
  env:
    workflowDepth: 1
    ALGoOrgSettings: 
    ALGoRepoSettings: 
    templateUrl: https://github.com/microsoft/AL-Go-PTE@main
    Settings: {"templateUrl":"https://github.com/microsoft/AL-Go-PTE@main"}
    _actor: curateideas
    _token: ***
    _parentTelemetryScopeJson: 7b2250[6](https://github.com/ctmcomputer/Sinnack-Business-Central/actions/runs/5462976688/jobs/9943098037#step:4:6)1[7](https://github.com/ctmcomputer/Sinnack-Business-Central/actions/runs/5462976688/jobs/9943098037#step:4:7)2616d6574657273223a7b7d2c22456d6974746564223a66616c73652c22436f7272656c6174696f6e4964223a2262666530373565632d373361612d343331642d3[8](https://github.com/ctmcomputer/Sinnack-Business-Central/actions/runs/5462976688/jobs/9943098037#step:4:8)6432362d386565626337323232616164222c22506172656e744[9](https://github.com/ctmcomputer/Sinnack-Business-Central/actions/runs/5462976688/jobs/9943098037#step:4:9)64223a22222c22416c6c506172616d6574657273223a7b7d2c22546f704964223a2262666530373565632d373361612d343331642d386432362d386565626337323232616164222c224e616d65223a22414c2d476f20776f726b666c6f772072616e3a2043494344222c22537461727454696d65223a225c2f446174652831363838353531343230323130295c2f222c2250726f70657274696573223a7b226576656e744964223a22444f30303931222c226263436f6e7461696e657248656c70657256657273696f6e223a22352e302e33222c22697341646d696e6973747261746f72223a2254727565222c22737461636b5472616365223a225b5c6e2020496e697454656c656d6574727953636f70652061742054656c656d6574727948656c7065722e7073313a206c696e65203231345c6e202043726561746553636f70652061742054656c656d6574727948656c7065722e70736d313a206c696e652037315c6e2020576f726b666c6f77496e697469616c697a652e70733120617420576f726b666c6f77496e697469616c697a652e7073313a206c696e652033375c6e202032363361373934632d643137362d346462632d613837632d3864316635663033303639612e7073312061742032363361373934632d643137362d346462632d613837632d3864316635663033303639612e7073313a206c696e6520325c6e20205c7530303363536372697074426c6f636b5c7530303365206174205c75303033634e6f2066696c655c75303033655c6e5d222c22414c476f56657273696f6e223a2276332e30222c2274797065223a22505445222c2274656d706c61746555726c223a2268747470733a2f2f6769746875622e636f6d2f6d6963726f736f66742f414c2d476f2d505445406d61696e222c227265706f7369746f7279223a2263746d636f6d70757465722f53696e6e61636b2d427573696e6573732d43656e7472616c222c2272756e417474656d7074223a2231222c2272756e4e756d626572223a223436222c2272756e4964223a2235343632393736363838227d2c224576656e744964223a22444f30303931227d
    _templateUrl: https://github.com/microsoft/AL-Go-PTE@main
    _templateBranch: 
    _update: N
    _updateBranch: main
    _directCommit: N
  
Downloading BcContainerHelper latest version from CDN
BcContainerHelper version 5.0.3
Setting defaultNewContainerParameters = @{dns=hostDNS}
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Error: CheckForUpdates action failed. Error: The property 'unusedALGoSystemFiles' cannot be found on this object. Verify that the property exists. Stacktrace: at <ScriptBlock>, C:\CTMBuildAgent03-1\_work\_actions\microsoft\AL-Go-Actions\v3.0\CheckForUpdates\CheckForUpdates.ps1: line 76 at <ScriptBlock>, C:\CTMBuildAgent03-1\_work\_temp\ebf44556-660b-46[10](https://github.com/ctmcomputer/Sinnack-Business-Central/actions/runs/5462976688/jobs/9943098037#step:4:10)-a9fc-8346b89e6fbb.ps1: line 2 at <ScriptBlock>, <No file>: line 1
AL-Go action ran: CheckForUpdates Telemetry Correlation Id: 61c5b901-d[12](https://github.com/ctmcomputer/Sinnack-Business-Central/actions/runs/5462976688/jobs/9943098037#step:4:12)f-45c0-95b8-978f6e6fd459
Removing BcContainerHelper
Error: Process completed with exit code 1.

**Comment by freddydk** [comment] 2023-07-05 11:46
Please try again - looks like a regression (which i fixed now)

**Comment by curateideas** [comment] 2023-07-05 12:03
Solved! Awesome! Thanks for your help.

**Closed** 2023-07-05 12:03 UTC
Labels: bug, Fix Ready, Shipped
