### ISSUE TITLE
The runtime version must be set to '9.0' or earlier in the app.json file

### ISSUE THREAD

**Issue by JLSolutionsNET** [microsoft/AL-Go#95] opened 2022-04-29 19:06 UTC
**Case**
Whenever I use one of your templates, create an app, create a local development environment and then publish the app to my local environment (Docker) manually with vscode I get the following error message in Visual Studio Code: 

**Error Message:** 
"The request for path /BC/dev/apps?tenant=default&SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: The runtime version of the extension package is currently set to '9.1'. The runtime version must be set to '9.0' or earlier in the app.json file in order to install the extension package on this server."

**My Solution**
In my case the solution is quite simple. I explicitly specify the runtime version 9.0 in the app.json. But is this the way to go? If so, should the Runtime be added back to the templates?

I have installed the latest "AL Language Extension" version v9.0.615906.

**Comment by freddydk** [comment] 2022-04-29 22:09
One of my next blog posts is going to be around BC version, runtime version etc.
What is your application dependency in your app?
What version of Business Central is spun up?

**Comment by JLSolutionsNET** [comment] 2022-04-29 22:20
My dependencies are the same as in the AL-Go-PTE template
 - "platform":  "1.0.0.0",
 - "**application**":  "19.0.0.0"

Im my case Business Central 20.0.37253.39863 US Sandbox spuns up

**Comment by StefanMaron** [comment] 2022-06-01 05:56
It seems like the default runtime is 9.1 if no runtime version is specified in the app.json. But runtime version 9.1 is not yet supported with BC20. I would say that this is a bug in the compiler. It should default to 9.0 right now

**Comment by freddydk** [comment] 2022-06-01 06:12
Do you see this error duing build in AL-Go or in VS Code?

**Comment by StefanMaron** [comment] 2022-06-01 07:24
I tested once again.

I had the problem only from within vs code. 
But it seems like this is not reproducible anymore since BC20.1 is released.

Also, in pipelines, even with a sandbox bc20 container I can not reproduce this anymore

**Comment by freddydk** [comment] 2022-06-01 07:27
So it seems like this was a bug in the marketplace vsix for 20.0 then.
Will close this issue then, thanks.

**Closed by freddydk** 2022-06-01 07:27 UTC
Labels: Cannot repro

**Comment by StefanMaron** [comment] 2022-06-01 07:29
As far as I can see there was no new release for the vsix yet.

And the error did only appear while publishing to BC, so I assume while the app was recompiled from the server
