### ISSUE TITLE
When creating a release, throw error if no new artifacts have been added

### ISSUE THREAD

**Issue by cegekaJG** [microsoft/AL-Go#608] opened 2023-07-18 14:25 UTC
Earlier I found out that if you use the action "Create Release", but haven't had a successful CI/CD since the last release, AL Go will tag the same commit and upload the same artifact from the previous release. However, the changelog in the release description will contain all commits up until the last commit of the target branch.
The workflow should first check if the targeted commit has already been tagged for a release, and throw an error if it has. If someone would want to use the same artifact in multiple releases, it should at least be an option to toggle this check.
Additionally, the changelog should only consist of commits between the last and current release.

**Comment by freddydk** [comment] 2023-07-18 16:05
The release notes is a duplicate of #559 - and was fixed by https://github.com/microsoft/AL-Go/pull/589
Will check whether the create release notes action could fail and state that no checkins have been made.

**Comment by freddydk** [comment] 2023-08-16 04:04
Shipped in v3.2

**Closed by freddydk** 2023-08-16 04:04 UTC
Labels: enhancement, In Progress, Shipped
