### ISSUE TITLE
LocalDevEnv.ps1 doesn't assignPremiumPlan  

### ISSUE THREAD

**Issue by jonaswre** [microsoft/AL-Go#349] opened 2023-01-11 09:49 UTC
I have the following AL-Go-Settings.json

```
{
  "type": "AppSource App",
  "templateUrl": "https://github.com/freddydk/AL-Go-AppSource@issue328",
  "useProjectDependencies": true,
  "assignPremiumPlan": true
}
```

But part of the log shows its not passed to the Run-AlPipeline
```
  _____                               _
 |  __ \                             | |
 | |__) |_ _ _ __ __ _ _ __ ___   ___| |_ ___ _ __ ___
 |  ___/ _` | '__/ _` | '_ ` _ \ / _ \ __/ _ \ '__/ __|
 | |  | (_| | | | (_| | | | | | |  __/ |_  __/ |  \__ \
 |_|   \__,_|_|  \__,_|_| |_| |_|\___|\__\___|_|  |___/

Pipeline name                   localDevEnv
Container name                  bcserver
Image name
ArtifactUrl                     https://bcartifacts.azureedge.net/sandbox/21.3.51409.51913/de
SasToken                        Not Specified
BcAuthContext                   Not Specified
Environment
ReUseContainer                  False
KeepContainer                   True
Auth                            UserPassword
Credential                      Specified
CompanyName
MemoryLimit                     8G
FailOn                          error
TreatTestFailuresAsWarnings     False
Enable Task Scheduler           False
Assign Premium Plan             False
```

I don't have overriding configuration in .Al-Go\settings.json

**Comment by freddydk** [comment] 2023-01-11 10:53
AssignPremiumPlan is not part of issue328 – is in a different branch.
Will be in preview later today (probably tonight)

**Comment by jonaswre** [comment] 2023-01-11 11:58
Is AssignPremiumPlan a new feature? I thought it was already supported before you opened the branch issue328.

What will be in preview tonight? #328 or/and AssignPremiumPlan? Because I don't think I can update before #328 is resolved.

**Comment by freddydk** [comment] 2023-01-11 12:02
AssignPremiumPlan was in Run-AlPipeline - but forgotten in AL-Go
Will be there tonight (incl. 328)

**Comment by freddydk** [comment] 2023-01-11 16:31
update AL-Go system files with microsoft/AL-Go-PTE@preview or microsoft/AL-Go-Appsource@preview and you should have #328 and this

**Comment by freddydk** [comment] 2023-01-11 16:37
Duplicate of #319

**Comment by freddydk** [comment] 2023-01-11 16:50
Hi @jonaswre - let me know when you have moved away from freddydk@issue328 - as I want to clean up orpheant branches
Thanks

**Comment by jonaswre** [comment] 2023-01-11 17:35
I'll switch tonight. 
But go ahead and delete it.

**Comment by jonaswre** [comment] 2023-01-11 18:54
I've moved
Thanks

**Comment by jonaswre** [comment] 2023-01-11 21:25
I'll try to reproduce this tomorrow in test repo. But after updating to preview this doesn't seem to be fixed for me.

**Comment by jonaswre** [comment] 2023-01-12 06:55
I can confirm this is not fixed. 
Aleast not for me. 

Please check https://github.com/byndit/AL-Go-Issue138 to see if its reproducible for you. 

I've executed AppA\.AL-Go\localDevEnv.ps1
And setting is set in .github\AL-Go-Settings.json

**Comment by freddydk** [comment] 2023-01-12 09:34
BTW - AssignPremiumPlan is a project setting, but you can set it in the repo setting (like you did), to take effect in all projects.

**Comment by jonaswre** [comment] 2023-01-12 10:41
> Could you try again? I applied a hotfix with a fix.

Didn't help


```
Downloading BcContainerHelper preview version from Blob Storage
Using 7zip
BcContainerHelper version 4.0.10-preview848
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Reading ..\.github\AL-Go-Settings.json
Reading .AL-Go\settings.json
Checking type
Checking appFolders and testFolders
Application Dependency 21.0.0.0
Checking artifact setting
Downloading artifacts from https://bcartifacts.azureedge.net/sandbox/21.3.51409.51979/de
Updating app- and test Dependencies
Analyzing Test App Dependencies
Checking project dependencies
Checking appDependencyProbingPaths
WARNING: No performance test apps found in bcptTestFolders in .AL-Go\settings.json
WARNING: No test apps found in testFolders in .AL-Go\settings.json
  _____                               _
 |  __ \                             | |
 | |__) |_ _ _ __ __ _ _ __ ___   ___| |_ ___ _ __ ___
 |  ___/ _` | '__/ _` | '_ ` _ \ / _ \ __/ _ \ '__/ __|
 | |  | (_| | | | (_| | | | | | |  __/ |_  __/ |  \__ \
 |_|   \__,_|_|  \__,_|_| |_| |_|\___|\__\___|_|  |___/

Pipeline name                   localDevEnv
Container name                  bcserver
Image name
ArtifactUrl                     https://bcartifacts.azureedge.net/sandbox/21.3.51409.51979/de
SasToken                        Not Specified
BcAuthContext                   Not Specified
Environment
ReUseContainer                  False
KeepContainer                   True
Auth                            UserPassword
Credential                      Specified
CompanyName
MemoryLimit                     8G
FailOn                          error
TreatTestFailuresAsWarnings     False
Enable Task Scheduler           False
Assign Premium Plan             False
```

**Comment by jonaswre** [comment] 2023-01-12 10:44
> BTW - AssignPremiumPlan is a project setting, but you can set it in the repo setting (like you did), to take effect in all projects.

Just do be sure I tried in both.

**Comment by freddydk** [comment] 2023-01-12 10:45
Clumsy me - it is fixed now.

**Closed** 2023-01-12 14:06 UTC
Labels: duplicate

**Comment by jonaswre** [comment] 2023-01-12 14:41
It works now!
