### ISSUE TITLE
Error AVS0118: Some dependencies could not be found for the country/region 'FR'

### ISSUE THREAD

**Issue by fofanasbsi** [microsoft/AL-Go#901] opened 2024-01-30 10:01 UTC
Hello Freddy,
I've been trying to migrate my app in AppSource in the CI/CD under github actions,when i run "Publish to AppSource" I'm getting this error in partner center 
--------------------------------------------
The validation of the submission failed with the following error(s): Error AVS0118: Some dependencies could not be found for the country/region 'FR' and release '22.5.0' of Business Central. Make sure that these dependencies are part of your submission or that they have already been uploaded to AppSource and that they are available for the targeted country/region and release: 'License Management' (50501856-fc24-47ca-8359-4809b382aa19) by 'SBSI Consulting' version '23.4.0.0'.

-------------------------------------------
the language of depencies is "fr" and the app too
-----------------------------------------

it's the full log: 
--------------------------------------------
Downloading BcContainerHelper latest version from CDN
Import from C:\ProgramData\BcContainerHelper\6.0.4\BcContainerHelper\BcContainerHelper.ps1
BcContainerHelper version 6.0.4
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Applying settings from D:\a\FinanceBasics\FinanceBasics\.github\AL-Go-Settings.json
Applying settings from D:\a\FinanceBasics\FinanceBasics\.AL-Go\settings.json
No settings found in D:\a\FinanceBasics\FinanceBasics\.github\Publish To AppSource.settings.json
No settings found in D:\a\FinanceBasics\FinanceBasics\.AL-Go\Publish To AppSource.settings.json
No settings found in D:\a\FinanceBasics\FinanceBasics\.AL-Go\fofanasbsi.settings.json
Artifacts current
Projects:
.
Project 'FinanceBasics'
Analyzing releases https://api.github.com/repos/SBSI-Consulting/FinanceBasics/releases
Downloading release v1, projects FinanceBasics, type Apps
project 'FinanceBasics'
AssetPatterns: 'FinanceBasics-*-Apps-*.zip' | 'FinanceBasics-Apps-*.zip'
https://api.github.com/repos/SBSI-Consulting/FinanceBasics/releases/assets/148674267
'D:\a\FinanceBasics\FinanceBasics\.artifacts\FinanceBasics-main-Apps-23.5.12.0.zip'
Artifacts:
- FinanceBasics-main-Apps-23.5.12.0
Applying settings from D:\a\FinanceBasics\FinanceBasics\.github\AL-Go-Settings.json
Applying settings from D:\a\FinanceBasics\FinanceBasics\.AL-Go\settings.json
No settings found in D:\a\FinanceBasics\FinanceBasics\.github\Publish To AppSource.settings.json
No settings found in D:\a\FinanceBasics\FinanceBasics\.AL-Go\Publish To AppSource.settings.json
No settings found in D:\a\FinanceBasics\FinanceBasics\.AL-Go\fofanasbsi.settings.json
Analyzing repository
No performance test apps found in bcptTestFolders in .AL-Go\settings.json
Azure.Storage Module is available in version 2.1.0
Using Azure.Storage version 2.1.0
Attempting authentication to https://api.partner.microsoft.com/.default using clientCredentials...
Authenticated as app ***
AppSource MainAppFolder .\Finance Basics
Main App File:
- SBSI Consulting_Finance Basics_23.6.12.0.app
Library App Files:
- None
Submitting to AppSource
GET https://api.partner.microsoft.com/v1.0/ingestion/products/xxxxxxx
GET https://api.partner.microsoft.com/v1.0/ingestion/products/xxxxxxx/setup
GET https://api.partner.microsoft.com/v1.0/ingestion/products/xxxxxxx/submissions
GET https://api.partner.microsoft.com/v1.0/ingestion/products/xxxxxxx/submissions/1152921505697304430
GET https://api.partner.microsoft.com/v1.0/ingestion/products/xxxxxxx/branches/getByModule(module=Package)
Downloading AL Language Extension (Prerelease) to C:\ProgramData\BcContainerHelper\alLanguageExtension\13.0.921843.zip
Downloading using WebClient
using 7zip
GET https://api.partner.microsoft.com/v1.0/ingestion/products/xxxxxxx/packageConfigurations/getByInstanceID(instanceID=4b1546bc-67f7-4d45-b31a-5116760677dd)
POST https://api.partner.microsoft.com/v1.0/ingestion/products/xxxxxxx/packages
{
    "fileName":  "SBSI Consulting_Finance Basics_23.6.12.0.app",
    "resourceType":  "Dynamics365BusinessCentralAddOnExtensionPackage"
}
WARNING: Microsoft Azure PowerShell collects data about how users use PowerShell cmdlets and some problems they 
encounter.  Microsoft uses this information to improve our PowerShell cmdlets.  Participation is voluntary and when you
 choose to participate your device automatically sends information to Microsoft about how you use Azure PowerShell. 

 

If you choose to participate, you can stop at any time by using Azure PowerShell as follows:

1. Use the Disable-AzureDataCollection cmdlet to turn the feature Off. The cmdlet can be found in the 
AzureResourceManager module

To disable data collection: PS > Disable-AzureDataCollection

If you choose to not participate, you can enable at any time by using Azure PowerShell as follows:

1. Use the Enable-AzureDataCollection cmdlet to turn the feature On. The cmdlet can be found in the 
AzureResourceManager module

To enable data collection: PS > Enable-AzureDataCollection

 

Select Y to enable data collection [Y/N]:
WARNING: You choose not to participate in Microsoft Azure PowerShell data collection.
WARNING: The setting profile has been saved to the following path 'C:\Users\runneradmin\AppData\Roaming\Windows Azure 
Powershell\AzureDataCollectionProfile.json'.
PUT https://api.partner.microsoft.com/v1.0/ingestion/products/xxxxxxx/packages/3af0df27-85c2-469e-9d6e-ee836deb73d8
{
    "id":  "3af0df27-85c2-469e-9d6e-ee836deb73d8",
    "fileName":  "SBSI Consulting_Finance Basics_23.6.12.0.app",
    "fileSasUri":  "https://ingestionpackagesprod1.blob.core.windows.net/file/3058306304102914289?sv=2018-03-28\u0026sr=b\u0026sig=WT%2FqVOjPxeOhRu2r79RD%2FmovSKud2cww7A3G4Bs4p1M%3D\u0026se=2024-01-31T09%3A37%3A16Z\u0026sp=rwl",
    "resourceType":  "Dynamics365BusinessCentralAddOnExtensionPackage",
    "state":  "Uploaded",
    "@odata.etag":  "\"b10[131](https://github.com/SBSI-Consulting/FinanceBasics/actions/runs/7708576948/job/21008966862#step:5:133)b7-0000-0800-0000-65b8bfc80000\""
}
PUT https://api.partner.microsoft.com/v1.0/ingestion/products/xxxxxxx/packageConfigurations/4b1546bc-67f7-4d45-b31a-5116760677dd
{
    "resourceType":  "Dynamics365BusinessCentralPackageConfiguration",
    "@odata.etag":  "\"e5067aa0-0000-0800-0000-65b8b2a10000\"",
    "packageType":  "AddOn",
    "id":  "4b1546bc-67f7-4d45-b31a-5116760677dd",
    "packageReferences":  [
                              {
                                  "value":  "3af0df27-85c2-469e-9d6e-ee836deb73d8",
                                  "type":  "Dynamics365BusinessCentralAddOnExtensionPackage"
                              }
                          ]
}
GET https://api.partner.microsoft.com/v1.0/ingestion/products/xxxxxxx/branches/getByModule(module=Property)
GET https://api.partner.microsoft.com/v1.0/ingestion/products/xxxxxxx/properties/getByInstanceID(instanceID=ef328ccc-6df3-0e2b-fafd-e5b8d449046a)
PUT https://api.partner.microsoft.com/v1.0/ingestion/products/xxxxxx/properties/ef328ccc-6df3-0e2b-fafd-e5b8d449046a
{
    "resourceType":  "AzureProperty",
    "hideKeys":  [

                 ],
    "categories":  [

                   ],
    "leveledCategories":  {
                              "Finance":  [
                                              "accounting"
                                          ]
                          },
    "extendedProperties":  [

                           ],
    "@odata.etag":  "\"0c0570bb-0000-0800-0000-65b27af60000\"",
    "useEnterpriseContract":  false,
    "globalAmendmentTerms":  "",
    "id":  "ef328ccc-6df3-0e2b-fafd-e5b8d449046a",
    "leveledIndustries":  {

                          },
    "termsOfUse":  "https://go.microsoft.com/fwlink/?linkid=2041178",
    "applicableProducts":  [

                           ],
    "industries":  [

                   ],
    "productTags":  [

                    ],
    "marketingOnlyChange":  false,
    "additionalCategories":  [

                             ],
    "appVersion":  "23.6.12.0",
    "submissionVersion":  "",
    "customAmendments":  [

                         ]
}
POST https://api.partner.microsoft.com/v1.0/ingestion/products/xxxxxxxx/submissions
{
    "resources":  [
                      {
                          "type":  "Package",
                          "value":  "4b1546bc-67f7-4d45-b31a-5116760677dd"
                      },
                      {
                          "type":  "Property",
                          "value":  "ef328ccc-6df3-0e2b-fafd-e5b8d449046a"
                      }
                  ],
    "targets":  [
                    {
                        "type":  "Scope",
                        "value":  "preview"
                    }
                ],
    "resourceType":  "SubmissionCreationRequest"
}
Automated validation......... Failure
New AppSource submission failed

resourceType       : Submission
state              : InProgress
substate           : Failed
targets            : {@{type=Scope; value=Preview}}
resources          : {@{type=Availability; value=280be3e2-6fbb-3cad-43d4-85b85d97fc8b}, @{type=Listing; 
                     value=13c8c3ba-058e-f9d9-ea89-dea5d4fa85ed}, @{type=Package; 
                     value=4b1546bc-67f7-4d45-b31a-5116760677dd}, @{type=Property; 
                     value=ef328ccc-6df3-0e2b-fafd-e5b8d449046a}...}
publishedTimeInUtc : 1601-01-01T00:00:00Z
pendingUpdateInfo  : @{updateType=Create; status=Completed}
releaseNumber      : 3
friendlyName       : Submission 3
areResourcesReady  : True
id                 : 115292150569732[140](https://github.com/SBSI-Consulting/FinanceBasics/actions/runs/7708576948/job/21008966862#step:5:142)1

**Comment by freddydk** [comment] 2024-02-01 08:14
If you upload your app manually to validation - does it then work?

**Comment by freddydk** [comment] 2024-02-01 08:17
It looks like the version of the license management app in AppSource isn't what you depend on:
You need:
License Management' (50501856-fc24-47ca-8359-4809b382aa19) by 'SBSI Consulting' version '23.4.0.0'.
AppSource has:
![image](https://github.com/microsoft/AL-Go/assets/10775043/31ad4ebd-0431-4af1-ac8b-6555793211dc)

Which is also the error you get.

**Comment by fofanasbsi** [comment] 2024-02-01 14:03
Thanks freddy, it works now, but I want to know why if I don't add manually it doesn't upload all the dependencies.
I would like to know what other possible solutions are available ?

**Comment by freddydk** [comment] 2024-02-02 08:32
Sorry, but I still don't know what the problem is/was?
I could see that your app had a dependency on an appSource app in a version, which hasn't been uploaded to AppSource.
When that is the case, validation will obviously reject your app.
This has nothing to do with automatic appsource submission or not.
If it worked after manually uploading the app, then you must have changed the dependency on the licensing app.
Will close this issue as it is unrelated to AL-Go.

**Closed by freddydk** 2024-02-02 08:32 UTC
Labels: question, Fix Ready, Unrelated to AL-Go
