### ISSUE TITLE
localDevEnv fails.

### ISSUE THREAD

**Issue by rolandpthompson** [microsoft/AL-Go#554] opened 2023-05-25 10:45 UTC
Trying to generate a local dev using the localDevEnv script.

But getting the following output error:

<img width="848" alt="image" src="https://github.com/microsoft/AL-Go/assets/6749639/2d5ed832-bc46-4bf5-a898-dadab21c85b9">

Can't get past this now.
I know I've used this in the past and it worked.
I can manually create an environment anyway, but curious if I've missed something?

**Comment by freddydk** [comment] 2023-05-26 04:32
Do you have GitHub CLI installed?
what happens if you run 

gh auth token 

in a command line or in powershell?

**Comment by freddydk** [comment] 2023-05-26 12:31
Now, that is a duplicate of #434 - you need to update to version 3.1, by running Update AL-Go System files.

**Comment by rolandpthompson** [comment] 2023-05-26 13:14
Updated, gets further.
Sits at the following for about a minute or so

<img width="737" alt="image" src="https://github.com/microsoft/AL-Go/assets/6749639/1eeee8af-7d5c-49b3-91bf-413a47e2c24f">

Then gives up

<img width="859" alt="image" src="https://github.com/microsoft/AL-Go/assets/6749639/6f6e0900-ed46-4fcc-b294-a107a316f588">

**Comment by freddydk** [comment] 2023-05-26 13:17
Looks like it tries to use Hyperv?
could you include the full output?

**Comment by rolandpthompson** [comment] 2023-05-26 13:18
Hmm, if I run it in windows ps from the terminal it seems to be working....

**Comment by rolandpthompson** [comment] 2023-05-26 13:18
_____                _   _                               _        _

  _                     _   _____             ______
 | |                   | | |  __ \           |  ____|
 | |     ___   ___ __ _| | | |  | | _____   __ |__   _ ____   __
 | |    / _ \ / __/ _` | | | |  | |/ _ \ \ / /  __| | '_ \ \ / /
 | |____ (_) | (__ (_| | | | |__| |  __/\ V /| |____| | | \ V /
 |______\___/ \___\__,_|_| |_____/ \___| \_/ |______|_| |_|\_/

This script will create a docker based local development environment for your project.

NOTE: You need to have Docker installed, configured and be able to create Business Central containers for this to work.
If this fails, you can setup a cloud based development environment by running cloudDevEnv.ps1

All apps and test apps will be compiled and published to the environment in the development scope.
The script will also modify launch.json to have a Local Sandbox configuration point to your environment.

Applying settings from D:\source\taigsolutions\Glenmuir\.github\AL-Go-Settings.json
Applying settings from D:\source\taigsolutions\Glenmuir\.AL-Go\settings.json
Checking System Requirements

Container name
--------------
Please enter the name of the container to create (default bcserver) 
bcserver selected

Authentication mechanism for container
--------------------------------------
a Username/Password authentication
b Windows Authentication

Select authentication mechanism for container (default a) 
Username/Password authentication selected


PowerShell credential request
Please enter username and password for your container
Password for user admin: *********

LicenseFileUrl
--------------
When developing PTEs, you can optionally specify a developer licensefile with permissions to object IDs of your dependant apps

Local path or a secure download URL to license file  (default none)
none selected

Downloading BcContainerHelper latest version from CDN
Using 7zip
BcContainerHelper version 5.0.3
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Running on PowerShell 7
Applying settings from D:\source\taigsolutions\Glenmuir\.github\AL-Go-Settings.json
Applying settings from D:\source\taigsolutions\Glenmuir\.AL-Go\settings.json
Not using Azure KeyVault, attempting to retrieve an auth token using gh auth token
Checking type
Checking appFolders, testFolders and bcptTestFolders
Application Dependency 22.0.0.0
Checking artifact setting for project
Downloading artifacts from https://bcartifacts.azureedge.net/sandbox/22.1.55890.57022/gb
Updating app- and test Dependencies
Analyzing Test App Dependencies
Checking project dependencies
Checking appDependencyProbingPaths
Dependency to projects '*' in https://github.com/taigsolutions/al-matrix@main, version latest, release status release
WARNING: No performance test apps found in bcptTestFolders in .AL-Go\settings.json
Downloading dependencies ...
Locating all Apps artifacts from probing paths
Analyzing releases https://api.github.com/repos/taigsolutions/al-matrix/releases
Downloading release v1.3, projects *, type Apps                                                                         
project '*'
https://api.github.com/repos/taigsolutions/al-matrix/releases/assets/104515260
Locating all TestApps artifacts from probing paths
Analyzing releases https://api.github.com/repos/taigsolutions/al-matrix/releases                                        
Downloading release v1.3, projects *, type TestApps                                                                     
project '*'                                                                                                             
  _____                               _
 |  __ \                             | |
 | |__) |_ _ _ __ __ _ _ __ ___   ___| |_ ___ _ __ ___
 |  ___/ _` | '__/ _` | '_ ` _ \ / _ \ __/ _ \ '__/ __|
 | |  | (_| | | | (_| | | | | | |  __/ |_  __/ |  \__ \
 |_|   \__,_|_|  \__,_|_| |_| |_|\___|\__\___|_|  |___/

Pipeline name                   localDevEnv                                                                             
Container name                  bcserver                                                                                
Image name                                                                                                              
ArtifactUrl                     https://bcartifacts.azureedge.net/sandbox/22.1.55890.57022/gb                           
SasToken                        Not Specified                                                                           
BcAuthContext                   Not Specified
Environment                                                                                                             
ReUseContainer                  False                                                                                   
KeepContainer                   True                                                                                    
useCompilerFolder               False                                                                                   
artifactCachePath                                                                                                       
useDevEndpoint                  True                                                                                    
Auth                            UserPassword                                                                            
Credential                      Specified                                                                               
CompanyName                                                                                                             
MemoryLimit                     8G                                                                                      
FailOn                          error                                                                                   
TreatTestFailuresAsWarnings     False                                                                                   
Enable Task Scheduler           False                                                                                   
Assign Premium Plan             False                                                                                   
Install Test Runner             True                                                                                    
Install Test Framework          True
Install Test Libraries          True                                                                                    
Install Perf. Toolkit           False                                                                                   
InstallOnlyReferencedApps       True                                                                                    
generateDependencyArtifact      False                                                                                   
CopySymbolsFromContainer        False                                                                                   
enableCodeCop                   False                                                                                   
enableAppSourceCop              False                                                                                   
enableUICop                     False                                                                                   
enablePerTenantExtensionCop     True
doNotPerformUpgrade             False                                                                                   
doNotPublishApps                False                                                                                   
uninstallRemovedApps            False                                                                                   
escapeFromCops                  False                                                                                   
doNotBuildTests                 False                                                                                   
doNotRunTests                   True                                                                                    
doNotRunBcptTests               True
useDefaultAppSourceRuleSet      False                                                                                   
rulesetFile                                                                                                             
azureDevOps                     False                                                                                   
gitLab                          False                                                                                   
gitHubActions                   False                                                                                   
vsixFile                                                                                                                
License file                    Not specified
CodeSignCertPfxFile             Not specified                                                                           
CodeSignCertPfxPassword         Not specified                                                                           
CodeSignCertIsSelfSigned        False                                                                                   
KeyVaultCertPfxFile             Not specified                                                                           
KeyVaultCertPfxPassword         Not specified                                                                           
KeyVaultClientId                                                                                                        
BuildOutputFile                                                                                                         
ContainerEventLogFile                                                                                                   
TestResultsFile                 D:\source\taigsolutions\Glenmuir\TestResults.xml                                        
BcptTestResultsFile             D:\source\taigsolutions\Glenmuir\bcptTestResults.json                                   
TestResultsFormat               JUnit                                                                                   
AdditionalCountries                                                                                                     
PackagesFolder                  .packages                                                                               
OutputFolder                                                                                                            
BuildArtifactFolder
CreateRuntimePackages           False                                                                                   
AppVersion                                                                                                              
AppBuild                        0                                                                                       
AppRevision                     0                                                                                       
Install Apps                                                                                                            
- D:\source\taigsolutions\Glenmuir\.dependencies\al-matrix-main-Apps-1.3.11.0.zip                                       
Install Test Apps                                                                                                       
- None                                                                                                                  
Previous Apps
- None                                                                                                                  
Application folders                                                                                                     
- D:\source\taigsolutions\Glenmuir\Base                                                                                 
- D:\source\taigsolutions\Glenmuir\DataImport                                                                           
- D:\source\taigsolutions\Glenmuir\ecommerce                                                                            
- D:\source\taigsolutions\Glenmuir\glenmuirpro                                                                          
Test application folders                                                                                                
- D:\source\taigsolutions\Glenmuir\Base.Test                                                                            
BCPT Test application folders                                                                                           
- None                                                                                                                  
BCPT Test suites                                                                                                        
- None                                                                                                                  
Custom CodeCops                                                                                                         
- None                                                                                                                  
                                                                                                                        
  _____       _ _ _                                          _        _
 |  __ \     | | (_)                                        (_)      (_)
 | |__) |   _| | |_ _ __   __ _    __ _  ___ _ __   ___ _ __ _  ___   _ _ __ ___   __ _  __ _  ___
 |  ___/ | | | | | | '_ \ / _` |  / _` |/ _ \ '_ \ / _ \ '__| |/ __| | | '_ ` _ \ / _` |/ _` |/ _ \
 | |   | |_| | | | | | | | (_| | | (_| |  __/ | | |  __/ |  | | (__  | | | | | | | (_| | (_| |  __/
 |_|    \__,_|_|_|_|_| |_|\__, |  \__, |\___|_| |_|\___|_|  |_|\___| |_|_| |_| |_|\__,_|\__, |\___|
                           __/ |   __/ |                                                 __/ |
                          |___/   |___/                                                 |___/

Pulling mcr.microsoft.com/businesscentral:10.0.20348.1726

Pulling generic image took 1 seconds
                                                                                                                        
   _____                _   _                               _        _
  / ____|              | | (_)                             | |      (_)
 | |     _ __ ___  __ _| |_ _ _ __   __ _    ___ ___  _ __ | |_ __ _ _ _ __   ___ _ __
 | |    | '__/ _ \/ _` | __| | '_ \ / _` |  / __/ _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
 | |____| | |  __/ (_| | |_| | | | | (_| | | (__ (_) | | | | |_ (_| | | | | |  __/ |
  \_____|_|  \___|\__,_|\__|_|_| |_|\__, |  \___\___/|_| |_|\__\__,_|_|_| |_|\___|_|
                                     __/ |
                                    |___/

Creaing docker container
BcContainerHelper is version 5.0.3
BcContainerHelper is running as administrator                                                                           
New-BcContainer Telemetry Correlation Id: de3e09dd-8a9b-4fbd-bdc1-33b91f2d618e
Run-AlPipeline Telemetry Correlation Id: e3d5de66-085d-4610-b8a9-659da56f23c0
Removing BcContainerHelper                                                                                              
Error: Class not registered

Stacktrace: at Get-HypervState, C:\Users\me\AppData\Local\Temp\b7ff1584-d789-4bfd-9c23-220042a75a9a\BcContainerHelper\BcContainerHelper.psm1: line 34
at New-BcContainer, C:\Users\me\AppData\Local\Temp\b7ff1584-d789-4bfd-9c23-220042a75a9a\BcContainerHelper\ContainerHandling\New-NavContainer.ps1: line 483
at <ScriptBlock>, C:\Users\me\AppData\Local\Temp\b7ff1584-d789-4bfd-9c23-220042a75a9a\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 693
at <ScriptBlock>, C:\Users\me\AppData\Local\Temp\b7ff1584-d789-4bfd-9c23-220042a75a9a\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 915
at <ScriptBlock>, C:\Users\me\AppData\Local\Temp\b7ff1584-d789-4bfd-9c23-220042a75a9a\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 845
at <ScriptBlock>, C:\Users\me\AppData\Local\Temp\b7ff1584-d789-4bfd-9c23-220042a75a9a\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 827
at Run-AlPipeline, C:\Users\me\AppData\Local\Temp\b7ff1584-d789-4bfd-9c23-220042a75a9a\BcContainerHelper\AppHandling\Run-AlPipeline.ps1: line 789
at CreateDevEnv, C:\Users\me\AppData\Local\Temp\tmp207D.tmp.ps1: line 1669
at <ScriptBlock>, D:\source\taigsolutions\Glenmuir\.AL-Go\localDevEnv.ps1: line 126
at <ScriptBlock>, <No file>: line 1

**Comment by freddydk** [comment] 2023-05-26 13:20
If you run this command on your machine:

Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V -Online

what does that return?

**Comment by rolandpthompson** [comment] 2023-05-26 13:21
<img width="824" alt="image" src="https://github.com/microsoft/AL-Go/assets/6749639/80d3fe61-8672-4498-b1bb-d6dd6c005093">

**Comment by rolandpthompson** [comment] 2023-05-26 13:40
Very
So it would seem if I use Windows Powershell it works, but if I use Powershell core - which was the default - it fails.
No idea why though

**Comment by rolandpthompson** [comment] 2023-05-26 13:41
Windows powershell set as the default in vscode also seems to work too.

**Comment by freddydk** [comment] 2023-07-02 13:55
This looks like this issue: https://github.com/PowerShell/PowerShell/issues/13866
(unrelated to AL-Go)

If you update PowerShell 7 to 7.3 - it should work again.

**Closed by freddydk** 2023-07-02 13:55 UTC
Labels: Unrelated to AL-Go
